DROP TABLE IF EXISTS `CONTRACT_ADDRESS`;

CREATE TABLE IF NOT EXISTS `CONTRACT_ADDRESS` (
  `ID`               BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID`             VARCHAR(55) NULL,
  `CONTRACT_ENTITY_ID` BIGINT(20) UNSIGNED NOT NULL,
  `ADDRESS_TYPE` VARCHAR(55) NOT NULL ,
  `ADDRESS_1` VARCHAR(255) NULL ,
  `ADDRESS_2` VARCHAR(255) NULL ,
  `CITY` VARCHAR (255) null,
  `STATE` VARCHAR (55) null,
  `ZIP` VARCHAR (55) null,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ADDRESS_CONTRACT_ENTITY` FOREIGN KEY (`CONTRACT_ENTITY_ID`)
  REFERENCES `CONTRACT_ENTITY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `POINT_OF_CONTACT`;

CREATE TABLE IF NOT EXISTS `POINT_OF_CONTACT` (
  `ID`               BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID`             VARCHAR(55) NULL,
  `CONTRACT_ENTITY_ID` BIGINT(20) UNSIGNED NOT NULL,
  `NAME` VARCHAR(255) NOT NULL ,
  `ROLE` VARCHAR(55) NULL ,
  `PHONE` VARCHAR(55) NULL ,
  `EMAIL` VARCHAR (255) null,
  `POC_TYPE` VARCHAR (55) null,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_POC_CONTRACT_ENTITY` FOREIGN KEY (`CONTRACT_ENTITY_ID`)
  REFERENCES `CONTRACT_ENTITY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

UPDATE PROGRAM_AGGREGATOR
SET MAILING_STATE = REPLACE(UPPER(MAILING_STATE), ' ', '_');