CREATE TABLE IF NOT EXISTS `CONTRACT_ENTITY` (
  `ID`               BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID`             VARCHAR(55) NULL,
  `BUSINESS_NAME` VARCHAR(55) NOT NULL ,
  `DBA` VARCHAR(55) NOT NULL ,
  `PARENT_ID`  BIGINT(20) UNSIGNED null,
  `SECTOR` VARCHAR (55) null,
  `TAX_ID` VARCHAR (55) null,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_PARENT_CONTRACT_ENTITY` FOREIGN KEY (`PARENT_ID`)
  REFERENCES `CONTRACT_ENTITY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;