CREATE TABLE `ENERGY_CONTRACT_CREDIT` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `ENERGY_CONTRACT_ID` bigint(20) unsigned NOT NULL,
  `CREDIT_TYPE` varchar(255) NOT NULL,
  `AMOUNT` decimal(20,6) DEFAULT NULL,
  `AMOUNT_TYPE` varchar(255) NOT NULL DEFAULT '',
  `UNIT_OF_MEASURE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ENERGY_CONTRACT_CREDIT_ENERGY_CONTRACT` (`ENERGY_CONTRACT_ID`),
  CONSTRAINT `FK_ENERGY_CONTRACT_CREDIT_ENERGY_CONTRACT` FOREIGN KEY (`ENERGY_CONTRACT_ID`) REFERENCES `ENERGY_CONTRACT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=9163 DEFAULT CHARSET=utf8;

CREATE TABLE `ENERGY_CONTRACT_BILL_MONTH` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `ENERGY_CONTRACT_ID` bigint(20) unsigned NOT NULL,
  `MONTH` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ENERGY_CONTRACT_BILL_MONTH_ENERGY_CONTRACT` (`ENERGY_CONTRACT_ID`),
  CONSTRAINT `FK_ENERGY_CONTRACT_BILL_MONTH_ENERGY_CONTRACT` FOREIGN KEY (`ENERGY_CONTRACT_ID`) REFERENCES `ENERGY_CONTRACT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=9162 DEFAULT CHARSET=utf8;

CREATE TABLE `ENERGY_CONTRACT_FEE` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `ENERGY_CONTRACT_ID` bigint(20) unsigned NOT NULL,
  `FEE_TYPE` varchar(255) NOT NULL,
  `AMOUNT` decimal(20,6) DEFAULT NULL,
  `AMOUN_TYPE` varchar(255) NOT NULL,
  `INDEX` varchar(255) DEFAULT NULL,
  `UNIT_OF_MEASURE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ENERGY_CONTRACT_FEE_ENERGY_CONTRACT` (`ENERGY_CONTRACT_ID`),
  CONSTRAINT `FK_ENERGY_CONTRACT_FEE_ENERGY_CONTRACT` FOREIGN KEY (`ENERGY_CONTRACT_ID`) REFERENCES `ENERGY_CONTRACT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `ENERGY_CONTRACT` ADD COLUMN `AGREEMENT_START_DATE` datetime DEFAULT NULL;
ALTER TABLE `ENERGY_CONTRACT` ADD COLUMN `AGREEMENT_END_DATE` datetime DEFAULT NULL;
ALTER TABLE `ENERGY_CONTRACT` ADD COLUMN `PAYMENT_FREQUENCY` varchar(255) DEFAULT NULL;
ALTER TABLE `ENERGY_CONTRACT` ADD COLUMN `CONTRACT_TERM` int(11) DEFAULT NULL;
ALTER TABLE `ENERGY_CONTRACT` ADD COLUMN `BILL_DAY_OF_MONTH` int(11) DEFAULT NULL;