ALTER TABLE `ENERGY_CONTRACT_PARTY` MODIFY COLUMN `ROLE` varchar(255) NOT NULL DEFAULT '';

CREATE TABLE `ENERGY_CONTRACT_RELATED_CONTRACTS` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `ENERGY_CONTRACT_ID` bigint(20) unsigned NOT NULL,
  `TYPE` varchar(255) NOT NULL,
  `RELATED_ENERGY_CONTRACT_ID` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ENERGY_CONTRACT_RELATED_CONTRACTS_ENERGY_CONTRACT` (`ENERGY_CONTRACT_ID`),
  KEY `FK_ENERGY_CONTRACT_RELATED_CONTRACTS_RELATED_ENERGY_CONTRACT` (`RELATED_ENERGY_CONTRACT_ID`),
  CONSTRAINT `FK_ENERGY_CONTRACT_RELATED_CONTRACTS_ENERGY_CONTRACT` FOREIGN KEY (`ENERGY_CONTRACT_ID`) REFERENCES `ENERGY_CONTRACT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ENERGY_CONTRACT_RELATED_CONTRACTS_RELATED_ENERGY_CONTRACT` FOREIGN KEY (`RELATED_ENERGY_CONTRACT_ID`) REFERENCES `ENERGY_CONTRACT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=9126 DEFAULT CHARSET=utf8;