ALTER TABLE `ENERGY_CONTRACT_COMMODITY` CHANGE `PRODUCT` `COMMODITY_TYPE` varchar(255) NOT NULL;

CREATE TABLE `COMMODITY_PROGRAM` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `COMMODITY_PROGRAM` SET `UUID` = UUID(), `NAME` = "Day Of";
INSERT INTO `COMMODITY_PROGRAM` SET `UUID` = UUID(), `NAME` = "Day Ahead";
INSERT INTO `COMMODITY_PROGRAM` SET `UUID` = UUID(), `NAME` = "Energy Reserves";
INSERT INTO `COMMODITY_PROGRAM` SET `UUID` = UUID(), `NAME` = "STOP";
INSERT INTO `COMMODITY_PROGRAM` SET `UUID` = UUID(), `NAME` = "ETC";
INSERT INTO `COMMODITY_PROGRAM` SET `UUID` = UUID(), `NAME` = "List Item1";

CREATE TABLE `COMMODITY_SUB_PROGRAM` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `COMMODITY_SUB_PROGRAM` SET `UUID` = UUID(), `NAME` = "List Item1";
INSERT INTO `COMMODITY_SUB_PROGRAM` SET `UUID` = UUID(), `NAME` = "STOP Runway";
INSERT INTO `COMMODITY_SUB_PROGRAM` SET `UUID` = UUID(), `NAME` = "Fast Reserve";
INSERT INTO `COMMODITY_SUB_PROGRAM` SET `UUID` = UUID(), `NAME` = "Demand Turn Up";
INSERT INTO `COMMODITY_SUB_PROGRAM` SET `UUID` = UUID(), `NAME` = "Demand Side Balancing Reserve";

ALTER TABLE `ENERGY_CONTRACT_COMMODITY` ADD COLUMN `COMMODITY_PROGRAM_ID` bigint(20) unsigned NOT NULL;
ALTER TABLE `ENERGY_CONTRACT_COMMODITY` ADD COLUMN `COMMODITY_SUB_PROGRAM_ID` bigint(20) unsigned NOT NULL;

ALTER TABLE `ENERGY_CONTRACT_COMMODITY` ADD COLUMN `COMMODITY_POWER_SOURCE` varchar(255) NOT NULL;


CREATE TABLE `ENERGY_CONTRACT_QUANTITY` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `ENERGY_CONTRACT_COMMODITY_ID` bigint(20) unsigned NOT NULL,
  `MINIMUM_QUALITY` decimal(7,2) NOT NULL,
  `MINIMUM_QUALITY_UNIT` varchar(255) NOT NULL,
  `MAXIMUM_QUALITY` decimal(7,2) NOT NULL,
  `MAXIMUM_QUALITY_UNIT` varchar(255) NOT NULL,
  `DATE_FROM` datetime NOT NULL,
  `DATE_TO` datetime NOT NULL,
  `COMMODITY_FREQUENCY` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ENERGY_CONTRACT_QUANTITY_COMMODITY` (`ENERGY_CONTRACT_COMMODITY_ID`),
  CONSTRAINT `FK_ENERGY_CONTRACT_QUANTITY_COMMODITY` FOREIGN KEY (`ENERGY_CONTRACT_COMMODITY_ID`) REFERENCES `ENERGY_CONTRACT_COMMODITY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=9254 DEFAULT CHARSET=utf8;

ALTER TABLE `ENERGY_CONTRACT_COMMODITY` DROP `MINIMUM_QUALITY`;
ALTER TABLE `ENERGY_CONTRACT_COMMODITY` DROP `MINIMUM_QUALITY_UNIT`;
ALTER TABLE `ENERGY_CONTRACT_COMMODITY` DROP `MAXIMUM_QUALITY`;
ALTER TABLE `ENERGY_CONTRACT_COMMODITY` DROP `MAXIMUM_QUALITY_UNIT`;
ALTER TABLE `ENERGY_CONTRACT_COMMODITY` DROP `DATE_FROM`;
ALTER TABLE `ENERGY_CONTRACT_COMMODITY` DROP `DATE_TO`;