CREATE TABLE `ENERGY_CONTRACT` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `TYPE` varchar(255) NOT NULL,
  `LAST_UPDATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9119 DEFAULT CHARSET=utf8;

CREATE TABLE `ENERGY_CONTRACT_COMMODITY` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `ENERGY_CONTRACT_ID` bigint(20) unsigned NOT NULL,
  `PRODUCT` varchar(255) NOT NULL,
  `MINIMUM_QUALITY` decimal(7,2) NOT NULL,
  `MINIMUM_QUALITY_UNIT` varchar(255) NOT NULL,
  `MAXIMUM_QUALITY` decimal(7,2) NOT NULL,
  `MAXIMUM_QUALITY_UNIT` varchar(255) NOT NULL,
  `DATE_FROM` datetime NOT NULL,
  `DATE_TO` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ENERGY_CONTRACT_COMMODITY_ENERGY_CONTRACT` (`ENERGY_CONTRACT_ID`),
  CONSTRAINT `FK_ENERGY_CONTRACT_COMMODITY_ENERGY_CONTRACT` FOREIGN KEY (`ENERGY_CONTRACT_ID`) REFERENCES `ENERGY_CONTRACT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ENERGY_CONTRACT_PARTY` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `ENERGY_CONTRACT_ID` bigint(20) unsigned NOT NULL,
  `ENTITY` varchar(255) NOT NULL,
  `ROLE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ENERGY_CONTRACT_PARTY_ENERGY_CONTRACT` (`ENERGY_CONTRACT_ID`),
  CONSTRAINT `FK_ENERGY_CONTRACT_PARTY_ENERGY_CONTRACT` FOREIGN KEY (`ENERGY_CONTRACT_ID`) REFERENCES `ENERGY_CONTRACT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;