ALTER TABLE `ENERGY_CONTRACT_PARTY` CHANGE `ENTITY` `ENTITY_ID` bigint(20) unsigned NOT NULL;

ALTER TABLE `ENERGY_CONTRACT_PARTY` ADD CONSTRAINT `ENERGY_CONTRACT_PARTY_ENTITY_ID`
FOREIGN KEY (`ENTITY_ID`) REFERENCES `CONTRACT_ENTITY` (`ID`)
ON DELETE NO ACTION ON UPDATE NO ACTION;