package com.caiso.soa.retrievebatchvalidationstatus_v1_wsdl;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-01-17T15:35:11.140Z
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "retrieveBatchValidationStatus_v1Service", 
                  wsdlLocation = "file:/Users/Antonio/Downloads/BatchValidationStatus/retrieveBatchValidationStatus_v1.wsdl",
                  targetNamespace = "http://www.caiso.com/soa/retrieveBatchValidationStatus_v1.wsdl") 
public class RetrieveBatchValidationStatusV1Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.caiso.com/soa/retrieveBatchValidationStatus_v1.wsdl", "retrieveBatchValidationStatus_v1Service");
    public final static QName RetrieveBatchValidationStatusServicePort = new QName("http://www.caiso.com/soa/retrieveBatchValidationStatus_v1.wsdl", "retrieveBatchValidationStatusServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/Antonio/Downloads/BatchValidationStatus/retrieveBatchValidationStatus_v1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RetrieveBatchValidationStatusV1Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/Antonio/Downloads/BatchValidationStatus/retrieveBatchValidationStatus_v1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RetrieveBatchValidationStatusV1Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RetrieveBatchValidationStatusV1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RetrieveBatchValidationStatusV1Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RetrieveBatchValidationStatusV1Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RetrieveBatchValidationStatusV1Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RetrieveBatchValidationStatusV1Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns RetrieveBatchValidationStatusV1
     */
    @WebEndpoint(name = "retrieveBatchValidationStatusServicePort")
    public RetrieveBatchValidationStatusV1 getRetrieveBatchValidationStatusServicePort() {
        return super.getPort(RetrieveBatchValidationStatusServicePort, RetrieveBatchValidationStatusV1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RetrieveBatchValidationStatusV1
     */
    @WebEndpoint(name = "retrieveBatchValidationStatusServicePort")
    public RetrieveBatchValidationStatusV1 getRetrieveBatchValidationStatusServicePort(WebServiceFeature... features) {
        return super.getPort(RetrieveBatchValidationStatusServicePort, RetrieveBatchValidationStatusV1.class, features);
    }

}
