package com.caiso.soa.retrievebatchvalidationstatus_v1_wsdl;

import com.caiso.soa.custom.responses.RetrieveBatchStatusInternalResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-01-17T15:35:11.126Z
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://www.caiso.com/soa/retrieveBatchValidationStatus_v1.wsdl", name = "retrieveBatchValidationStatus_v1")
@XmlSeeAlso({com.caiso.soa.batchvalidationstatus_v1.ObjectFactory.class, com.caiso.soa._2006_06_13.standardattachmentinfor.ObjectFactory.class, com.caiso.soa.standardoutput_v1.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT, parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RetrieveBatchValidationStatusV1 {

    /**
     * retrieve BatchValidationStatus data
     */
    @WebMethod(operationName = "retrieveBatchValidationStatus_v1", action = "http://www.caiso.com/soa/retrieveBatchValidationStatus_v1")
    @WebResult(name = "DRBatchStatus_attachmentResponse", targetNamespace = "http://www.caiso.com/soa/BatchValidationStatus_v1.xsd", partName = "DRBatchStatus_attachmentResponse")
    public RetrieveBatchStatusInternalResponse retrieveBatchValidationStatusV1(
            @WebParam(partName = "BatchValidationStatus", name = "BatchValidationStatus", targetNamespace = "http://www.caiso.com/soa/BatchValidationStatus_v1.xsd#")
                    com.caiso.soa.batchvalidationstatus_v1.BatchValidationStatus requestData
    ) throws FaultReturnType;
}
