CREATE TABLE IF NOT EXISTS `PROGRAM_AGGREGATOR` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(55) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `MAILING_ADDRES` VARCHAR(255) NULL,
  `MAILING_CITY` VARCHAR(255) NULL,
  `MAILING_STATE` VARCHAR(255) NULL,
  `MAILING_ZIP_CODE` VARCHAR(255) NULL,
  `PRIMARY_POC` VARCHAR(255) NULL,
  `PRIMARY_POC_PHONE` VARCHAR(255) NULL,
  `EFFECTIVE_START_DATE` TIMESTAMP NULL,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `PROGRAM_SA_ENROLLMENT` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_ID` BIGINT(20) NOT NULL,
  `AGGREGATOR_ID` BIGINT(20) NULL,
  `SA_ID` VARCHAR(10) NOT NULL,
  `ENROLLMENT_SOURCE` VARCHAR(255) NULL,
  `ENROLLMENT_CHANNEL` VARCHAR(255) NULL,
  `ENROLLMENT_STATUS` VARCHAR(255) NULL,
  `EFFECTIVE_START_DATE` TIMESTAMP NULL,
  `EFFECTIVE_END_DATE` TIMESTAMP NULL,
  `DRMS_ID` VARCHAR(45) NULL,
  `UNENROLL_REASON` VARCHAR(255) NULL,
  `FSL` VARCHAR(255) NULL,
  `THIRD_PARTY_NAME` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  INDEX `IDX_SA_ENROLLMENT_PROGRAM` (`PROGRAM_ID` ASC),
  CONSTRAINT `FK_SA_ENROLLMENT_PROGRAM`
    FOREIGN KEY (`PROGRAM_ID`)
    REFERENCES `PROGRAM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `IDX_SA_ENROLLMENT_AGGREGATOR` (`AGGREGATOR_ID` ASC),
  CONSTRAINT `FK_SA_ENROLLMENT_AGGREGATOR`
    FOREIGN KEY (`AGGREGATOR_ID`)
    REFERENCES `PROGRAM_AGGREGATOR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `IDX_SA_ENROLLMENT_SA` (`SA_ID` ASC),
  CONSTRAINT `FK_SA_ENROLLMENT_SA`
    FOREIGN KEY (`SA_ID`)
    REFERENCES `SERVICE_AGREEMENT` (`SERVICE_AGREEMENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `NOTES` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(55) NOT NULL,
  `ENTITY` VARCHAR(255) NOT NULL,
  `ENTITY_ID` VARCHAR(20) NOT NULL,
  `TITLE` VARCHAR(255) NULL,
  `DESCRIPTION` VARCHAR(1000) NULL,
  `AUTHOR` VARCHAR(255) NOT NULL,
  `CREATION_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `PROGRAM_SA_ENROLLMENT_ATTRIBUTE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(55) NOT NULL,
  `SA_ENROLLMENT_ID` BIGINT(20) NOT NULL,
  `_KEY` VARCHAR(255) NULL,
  `_VALUE` VARCHAR(1000) NULL,
  PRIMARY KEY (`ID`),
  INDEX `IDX_ATTRIBUTE_SA_ENROLLMENT` (`SA_ENROLLMENT_ID` ASC),
  CONSTRAINT `FK_ATTRIBUTE_SA_ENROLLMENT`
    FOREIGN KEY (`SA_ENROLLMENT_ID`)
    REFERENCES `PROGRAM_SA_ENROLLMENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

ALTER TABLE `PROGRAM_AGGREGATOR` ADD COLUMN `WEBSITE` VARCHAR(255) NULL;
ALTER TABLE `PROGRAM_AGGREGATOR` ADD COLUMN `STATUS` VARCHAR(255) NULL;
ALTER TABLE `PROGRAM_AGGREGATOR` ADD COLUMN `EFFECTIVE_END_DATE` TIMESTAMP NULL;

ALTER TABLE `PROGRAM_SA_ENROLLMENT` ADD COLUMN `ORIGINAL_EFFECTIVE_START_DATE` TIMESTAMP NULL;


CREATE TABLE IF NOT EXISTS `PROGRAM_FIRM_SERVICE_LEVEL` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(55) NOT NULL,
  `APPLICATION_ID` BIGINT(20) NOT NULL,
  `EFFECTIVE_START_DATE` TIMESTAMP NULL,
  `EFFECTIVE_END_DATE` TIMESTAMP NULL,
  `LAST_UPDATED_DATE` TIMESTAMP NULL,
  `LAST_UPDATED_BY` VARCHAR (255) NOT NULL,
  `FSL_VALUE` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  INDEX `IDX_FSL_APPLICATION` (`APPLICATION_ID` ASC),
  CONSTRAINT `FK_FSL_APPLICATION`
    FOREIGN KEY (`APPLICATION_ID`)
    REFERENCES `PROGRAM_SA_ENROLLMENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `PROGRAM_ELIGIBILITY_SNAPSHOT` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(55) NOT NULL,
  `APPLICATION_ID` BIGINT(20) NOT NULL,
  `EFFECTIVE_DATE` TIMESTAMP NULL,
  `ATTRIBUTE` VARCHAR(255) NULL,
  `_VALUE` VARCHAR(255) NULL,
  `ELIGIBLE` TINYINT(1) NOT NULL DEFAULT 0,
  `OVERRIDE_REASON` VARCHAR(255) NULL,
  `OVERRIDE_USER` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  INDEX `IDX_ELIGIBILITY_APPLICATION` (`APPLICATION_ID` ASC),
  CONSTRAINT `FK_ELIGIBILITY_APPLICATION`
    FOREIGN KEY (`APPLICATION_ID`)
    REFERENCES `PROGRAM_SA_ENROLLMENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

  ALTER TABLE `PROGRAM_SA_ENROLLMENT` ADD INDEX `IDX_ENROLLMENT_STATUS` (ENROLLMENT_STATUS);

  ALTER TABLE PROGRAM_PROFILE DROP COLUMN ROTATING_BLOCK_PERCENTAGE;
  ALTER TABLE PROGRAM_PROFILE DROP COLUMN ROTATING_BLOCK_PERCENTAGE_REVIEW;
  ALTER TABLE PROGRAM_PROFILE DROP COLUMN SERVICE_LEVEL_MIN_VALIDATION;
  ALTER TABLE PROGRAM_PROFILE DROP COLUMN MIN_VALIDATION_VALUE;
  ALTER TABLE PROGRAM_PROFILE DROP COLUMN MIN_VALIDATION_BENCHMARK;
  ALTER TABLE PROGRAM_PROFILE DROP COLUMN SERVICE_LEVEL_MAX_VALIDATION;
  ALTER TABLE PROGRAM_PROFILE DROP COLUMN MAX_VALIDATION_VALUE;
  ALTER TABLE PROGRAM_PROFILE DROP COLUMN MAX_VALIDATION_BENCHMARK;

  ALTER TABLE PROGRAM_PROFILE ADD COLUMN ESSENTIAL_CUST_ROTATING_BLOCK VARCHAR(100) NULL;


  CREATE TABLE IF NOT EXISTS `PROGRAM_FSL_RULE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(55) NOT NULL,
  `PROFILE_ID` BIGINT(20) NOT NULL,
  `ESSENTIAL` TINYINT(1) NOT NULL DEFAULT 0,
  `TYPE` VARCHAR(100) NOT NULL, -- season, load at the moment
  `COMPARISON_ATTRIBUTE` VARCHAR(100) NOT NULL, -- at this moment will be FSL Commitment, giving no option to the user
  `COMPARISON_OPERATOR` VARCHAR(5) NOT NULL,
  `COMPARISON_VALUE` DECIMAL(7,2) NOT NULL,
  `COMPARISON_REFERENCE` VARCHAR(100) NULL,
  `ENERGY_UNIT` VARCHAR(5) NULL, -- kW,MW
  `SEASON_ID` BIGINT(20) NULL,
  `NEXT_RULE_LINK` VARCHAR(5) NULL,
  PRIMARY KEY (`ID`),
  INDEX `IDX_FSL_PROFILE` (`PROFILE_ID` ASC),
  CONSTRAINT `FK_FSL_PROFILE`
    FOREIGN KEY (`PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_FSL_SEASON`
    FOREIGN KEY (`SEASON_ID`)
    REFERENCES `PROGRAM_SEASON` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;