CREATE TABLE IF NOT EXISTS `MI_ISO_PROFILE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(55) NOT NULL,
  `ISO_ID` BIGINT(20) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `LAST_UPDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `EFFECTIVE_START_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EFFECTIVE_END_DATE` TIMESTAMP NULL,
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

ALTER TABLE `MI_ISO` ADD COLUMN `ACTIVE` tinyint(1) NOT NULL;

ALTER TABLE `MI_ISO_PROFILE` ADD COLUMN `MARKET_ELIGIBLE` tinyint(1) NOT NULL;
ALTER TABLE `MI_ISO_PROFILE` ADD COLUMN `PARTICIPATION_ACTIVE` tinyint(1) NOT NULL;
ALTER TABLE `MI_ISO_PROFILE` ADD COLUMN `DAY_AHEAD_PARTICIPATION` tinyint(1) NOT NULL;
ALTER TABLE `MI_ISO_PROFILE` ADD COLUMN `REAL_TIME_PARTICIPATION` tinyint(1) NOT NULL;

ALTER TABLE `MI_ISO_PROFILE` ADD COLUMN `PARTICIPATION_ACTIVE_DATE` TIMESTAMP NULL;
ALTER TABLE `MI_ISO_PROFILE` ADD COLUMN `MARKET_ELIGIBLE_DATE` TIMESTAMP NULL;

CREATE TABLE IF NOT EXISTS `MI_ISO_PROFILE_HOLIDAY` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `MI_ISO_PROFILE_ID` BIGINT(20) NOT NULL,
  `NAME` VARCHAR(255) NULL,
  `NERC` TINYINT(1) NULL,
  `DATE` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_MI_ISO_HOLIDAY_MI_ISO_PROFILE1_idx` (`MI_ISO_PROFILE_ID` ASC),
  CONSTRAINT `fk_MI_ISO_HOLIDAY_MI_ISO_PROFILE1`
    FOREIGN KEY (`MI_ISO_PROFILE_ID`)
    REFERENCES `MI_ISO_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;