DROP TABLE IF EXISTS `ELIGIBLE_PROGRAMS`;

CREATE TABLE `ELIGIBLE_PROGRAMS` (
  `ID`         BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID`       VARCHAR(55)         NOT NULL DEFAULT '',
  `PROGRAM_ID` BIGINT(20)          NOT NULL,
  `PROFILE_ID` BIGINT(20)          NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_EP_PROGRAM`
  FOREIGN KEY (`PROGRAM_ID`)
  REFERENCES `PROGRAM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PEP_PROFILE`
  FOREIGN KEY (`PROFILE_ID`)
  REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;



ALTER TABLE PROGRAM_PROFILE ADD COLUMN WHOLESALE_MARKET_ELIGIBLE tinyint(1) NOT NULL default 0;
ALTER TABLE PROGRAM_PROFILE ADD COLUMN WHOLESALE_MARKET_ELIGIBLE_TS TIMESTAMP NULL;
ALTER TABLE PROGRAM_PROFILE ADD COLUMN WHOLESALE_PARTICIPATION_ACTIVE tinyint(1) NOT NULL default 0;
ALTER TABLE PROGRAM_PROFILE ADD COLUMN WHOLESALE_PARTICIPATION_ACTIVE_TS TIMESTAMP NULL;
ALTER TABLE PROGRAM_PROFILE ADD COLUMN WHOLESALE_AUTORESOURCE_MAINTENAINCAE tinyint(1) NOT NULL default 0;
ALTER TABLE PROGRAM_PROFILE ADD COLUMN WHOLESALE_STATISTICAL_SAMPLING_METHOD tinyint(1) NOT NULL default 0;
ALTER TABLE PROGRAM_PROFILE ADD COLUMN WHOLESALE_CROSS_PROGRAM_AGGREGATION tinyint(1) NOT NULL default 0;