ALTER TABLE CUSTOMER_DATA ADD COLUMN CUSTOMER_MDMA_CODE VARCHAR(50);
ALTER TABLE CUSTOMER_DATA ADD COLUMN CUSTOMER_MSP_CODE VARCHAR(50);
ALTER TABLE CUSTOMER_DATA ADD COLUMN CUSTOMER_LSE_CODE VARCHAR(50);
ALTER TABLE SERVICE_POINT ADD COLUMN CUSTOMER_MDMA_CODE VARCHAR(50);
ALTER TABLE SERVICE_POINT ADD COLUMN CUSTOMER_MSP_CODE VARCHAR(50);
ALTER TABLE SERVICE_AGREEMENT ADD COLUMN CUSTOMER_LSE_CODE VARCHAR(50);