ALTER TABLE `MI_ISO_PROFILE` DROP COLUMN `PARTICIPATION_ACTIVE`;
ALTER TABLE `MI_ISO_PROFILE` DROP COLUMN `PARTICIPATION_ACTIVE_DATE`;
ALTER TABLE `MI_ISO_PROFILE` DROP COLUMN `DAY_AHEAD_PARTICIPATION`;
ALTER TABLE `MI_ISO_PROFILE` DROP COLUMN `REAL_TIME_PARTICIPATION`;
