DROP TABLE IF EXISTS MI_ISO;

CREATE TABLE MI_ISO (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  UUID varchar(55) NOT NULL,
  NAME varchar(255) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY MI_ISO_NAME_uindex (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;