ALTER TABLE SERVICE_AGREEMENT DROP COLUMN SMART_RATE_IND;
ALTER TABLE SERVICE_AGREEMENT DROP COLUMN SR_START_DATE;
ALTER TABLE SERVICE_AGREEMENT DROP COLUMN SR_END_DATE;
ALTER TABLE SERVICE_AGREEMENT DROP COLUMN SR_BILL_PROTECTION;
ALTER TABLE SERVICE_AGREEMENT DROP COLUMN PDP_ENROLLED;
ALTER TABLE SERVICE_AGREEMENT DROP COLUMN PDP_START_DATE;
ALTER TABLE SERVICE_AGREEMENT DROP COLUMN PDP_STOP_DATE;
ALTER TABLE SERVICE_AGREEMENT DROP COLUMN PDP_RESERVATION_CAPACITY_APPLIED_VALUE;
ALTER TABLE SERVICE_AGREEMENT DROP COLUMN PDP_STATUS;
ALTER TABLE SERVICE_AGREEMENT DROP COLUMN PDP_PLAN_OPTIONS;
ALTER TABLE SERVICE_AGREEMENT DROP COLUMN PDP_BILL_PROTECTION;


ALTER TABLE PROGRAM_SA_ENROLLMENT ADD COLUMN BILL_PROTECTION tinyint(1) NOT NULL default '0';
ALTER TABLE PROGRAM_SA_ENROLLMENT ADD COLUMN RESERVATION_CAPACITY_APPLIED_VALUE VARCHAR(12) NULL;
ALTER TABLE PROGRAM_SA_ENROLLMENT ADD COLUMN PLAN_OPTIONS VARCHAR(50) NULL;

INSERT INTO PROGRAM (UUID,NAME,ACTIVE,CAP_ACTIVE) VALUES('3d8b7020-eb1e-4447-b8c5-65664a9d4c86','PDP',1,0);
INSERT INTO PROGRAM (UUID,NAME,ACTIVE,CAP_ACTIVE) VALUES('79befa51-62a5-4c8c-82a5-efe586b4d24c','Smart Rate',1,0);


ALTER TABLE SERVICE_AGREEMENT ADD COLUMN ESSENTIAL_CUSTOMER_FLAG VARCHAR(50) NULL;
ALTER TABLE CUSTOMER_DATA ADD COLUMN ESSENTIAL_CUSTOMER_FLAG VARCHAR(50) NULL;