
CREATE TABLE IF NOT EXISTS `PROGRAM` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(55) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `ACTIVE` TINYINT(1) NOT NULL,
  `CAP_ACTIVE` TINYINT(1) NOT NULL,
  `CAP_NUMBER` DECIMAL(10,5),
  `CAP_UNIT` VARCHAR(10),
  PRIMARY KEY (`ID`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `PROGRAM_PROFILE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_ID` BIGINT(20) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `LAST_UPDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `EFFECTIVE_START_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EFFECTIVE_END_DATE` TIMESTAMP NULL,
  `APP_BACK_DATING_NEW_ENROLL` TINYINT(1) NOT NULL DEFAULT 0,
  `APP_BACK_DATING_UNENROLL` TINYINT(1) NOT NULL DEFAULT 0,
  `APP_FUTURE_DATING_NEW_ENROLL` TINYINT(1) NOT NULL DEFAULT 0,
  `APP_FUTURE_DATING_UNENROLL` TINYINT(1) NOT NULL DEFAULT 0,
  `ENROLLMENT_EFFECTIVE_DATE` VARCHAR(45) NULL,
  `EARLIEST_EFFECTIVE_DATE` VARCHAR(45) NULL,
  `SA_STATUS_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `SERVICE_TYPE` VARCHAR(45) NULL,
  `SERVICE_TYPE_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `CUSTOMER_TYPE` VARCHAR(45) NULL,
  `CUSTOMER_TYPE_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `RATE_SCHEDULE_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `PREMISE_TYPE_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `3RD_PARTY_DRP` VARCHAR(50) NULL DEFAULT NULL,
  `3RD_PARTY_DRP_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `MEDICAL_BASELINE` VARCHAR(50) NULL DEFAULT NULL,
  `MEDICAL_BASELINE_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `LIFE_SUPPORT` VARCHAR(50) NULL DEFAULT NULL,
  `LIFE_SUPPORT_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `ROTATING_BLOCK_PERCENTAGE` DECIMAL(5,2) NULL,
  `ROTATING_BLOCK_PERCENTAGE_REVIEW` TINYINT(1) NOT NULL DEFAULT 0,
  `ROLL_USE_FLAG_RESIDENTIAL` TINYINT(1) NOT NULL DEFAULT 0,
  `ROLL_USE_FLAG_RESIDENTIAL_SIGN` VARCHAR(2) NULL,
  `ROLL_USE_FLAG_RESIDENTIAL_VALUE` DECIMAL(5,2) NULL,
  `ROLL_USE_FLAG_COMMERCIAL` TINYINT(1) NOT NULL DEFAULT 0,
  `ROLL_USE_FLAG_COMMERCIAL_SIGN` VARCHAR(2) NULL,
  `ROLL_USE_FLAG_COMMERCIAL_VALUE` DECIMAL(5,2) NULL,
  `ROLL_USE_FLAG_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `EQUIPMENT_REQUIRED` TINYINT(1) NOT NULL DEFAULT 0,
  `EQUIPMENT_INSTALL_PRIOR_TO` VARCHAR(45) NULL,
  `EQUIPMENT_REQUIRED_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `DEMAND_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `SERVICE_LEVEL_COMMITMENT` TINYINT(1) NOT NULL DEFAULT 0,
  `SERVICE_LEVEL_MIN_VALIDATION` TINYINT(1) NOT NULL DEFAULT 0,
  `MIN_VALIDATION_VALUE` DECIMAL(5,2) NULL,
  `MIN_VALIDATION_BENCHMARK`  VARCHAR(45) NULL,
  `SERVICE_LEVEL_MAX_VALIDATION` TINYINT(1) NOT NULL DEFAULT 0,
  `MAX_VALIDATION_VALUE` DECIMAL(5,2) NULL,
  `MAX_VALIDATION_BENCHMARK`  VARCHAR(45) NULL,
  `SERVICE_LEVEL_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `MULTIPLE_PARTICIPATION_REVIEW_EXCEPTION` TINYINT(1) NOT NULL DEFAULT 0,
  `ELIGIBILITY_AUTO_RETRY` TINYINT(1) NOT NULL DEFAULT 0,
  `ELIGIBILITY_AUTO_RETRY_DAYS` VARCHAR(4) NULL,
  `MIN_METER_READ_CYCLE` VARCHAR(45) NULL,
  `CDW_NOTIFY_TYPE` VARCHAR(45) NULL,
  `CDW_NOTIFY_EMAIL` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_PROFILE_PROGRAM` (`PROGRAM_ID` ASC),
  CONSTRAINT `FK_PROFILE_PROGRAM`
    FOREIGN KEY (`PROGRAM_ID`)
    REFERENCES `PROGRAM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `PROGRAM_OPTION` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `TYPE` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_OPTION_PROFILE` (`PROGRAM_PROFILE_ID` ASC),
  CONSTRAINT `FK_OPTION_PROFILE`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `PROGRAM_PRODUCT` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` VARCHAR(55) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `PROGRAM_OPTION_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROGRAM_PRODUCTS_PROGRAM_OPTION1_idx` (`PROGRAM_OPTION_ID` ASC),
  CONSTRAINT `fk_PROGRAM_PRODUCTS_PROGRAM_OPTION1`
    FOREIGN KEY (`PROGRAM_OPTION_ID`)
    REFERENCES `PROGRAM_OPTION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `PROGRAM_SEASON` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `NAME` VARCHAR(255) NULL,
  `START_DATE` DATETIME NULL,
  `END_DATE` DATETIME NULL,
  `DISPATCH_MON` TINYINT(1) NULL,
  `DISPATCH_TUE` TINYINT(1) NULL,
  `DISPATCH_WED` TINYINT(1) NULL,
  `DISPATCH_THU` TINYINT(1) NULL,
  `DISPATCH_FRI` TINYINT(1) NULL,
  `DISPATCH_SAT` TINYINT(1) NULL,
  `DISPATCH_SUN` TINYINT(1) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROGRAM_SEASON_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID` ASC),
  CONSTRAINT `fk_PROGRAM_SEASON_PROGRAM_PROFILE1`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `PROGRAM_HOLIDAYS` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `NAME` VARCHAR(255) NULL,
  `NERC` TINYINT(1) NULL,
  `DATE` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROGRAM_HOLIDAYS_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID` ASC),
  CONSTRAINT `fk_PROGRAM_HOLIDAYS_PROGRAM_PROFILE1`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `PROGRAM_ENROLLERS` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROGRAM_ENROLLERS_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID` ASC),
  CONSTRAINT `fk_PROGRAM_ENROLLERS_PROGRAM_PROFILE1`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;



CREATE TABLE IF NOT EXISTS `PROGRAM_ELIG_SA_STATUS` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `STATUS` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROGRAM_ELIG_SA_STATUS_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID` ASC),
  CONSTRAINT `fk_PROGRAM_ELIG_SA_STATUS_PROGRAM_PROFILE1`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `PROGRAM_ELIG_RATE_SCHEDULE` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `RATE_SCHEDULE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROGRAM_RATE_SCHEDULE_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID` ASC),
  CONSTRAINT `fk_PROGRAM_RATE_SCHEDULE_PROGRAM_PROFILE1`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS `PROGRAM_ELIG_PREMISE_TYPE` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `PREMISE_TYPE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `PROGRAM_PREMISE_TYPE_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID` ASC),
  CONSTRAINT `fk_PROGRAM_PREMISE_TYPE_PROGRAM_PROFILE1`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;



CREATE TABLE IF NOT EXISTS `PROGRAM_DEMAND` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `CALCULATION_INDICATOR` VARCHAR(45) NULL,
  `CALCULATION_VALUE` VARCHAR(45) NULL,
  `MIN_VALUE` DECIMAL(5,2) NULL,
  `MIN_UNIT` VARCHAR(5) NULL,
  `DATE_FROM` DATETIME NULL,
  `DATE_TO` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROGRAM_DEMAND_CALCULATION_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID` ASC),
  CONSTRAINT `fk_PROGRAM_DEMAND_CALCULATION_PROGRAM_PROFILE1`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;



CREATE TABLE IF NOT EXISTS `PROGRAM_MULTI_PARTICIPATION` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `PROGRAM_OPTION_ID` BIGINT(20) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROGRAM_MULTI_PARTICIPATION_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID` ASC),
  INDEX `fk_PROGRAM_MULTI_PARTICIPATION_PROGRAM_OPTION1_idx` (`PROGRAM_OPTION_ID` ASC),
  CONSTRAINT `fk_PROGRAM_MULTI_PARTICIPATION_PROGRAM_PROFILE1`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROGRAM_MULTI_PARTICIPATION_PROGRAM_OPTION1`
    FOREIGN KEY (`PROGRAM_OPTION_ID`)
    REFERENCES `PROGRAM_OPTION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;



CREATE TABLE IF NOT EXISTS `PROGRAM_MULTI_PARTICIPATION_PROGRAM` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_ID` BIGINT(20) NOT NULL,
  `PROGRAM_MULTI_PARTICIPATION_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `PROGRAM_MULTI_PARTICIPATION_PROGRAM_PROGRAM_idx` (`PROGRAM_ID` ASC),
  INDEX `PROGRAM_MULTI_PARTICIPATION_PROGRAM_MULTI_PART_idx` (`PROGRAM_MULTI_PARTICIPATION_ID` ASC),
  CONSTRAINT `fk_PROGRAM_MULTI_PARTICIPATION_PROGRAM_PROGRAM`
    FOREIGN KEY (`PROGRAM_ID`)
    REFERENCES `PROGRAM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROGRAM_MULTI_PARTICIPATION_PROGRAM_MULTI_PART`
    FOREIGN KEY (`PROGRAM_MULTI_PARTICIPATION_ID`)
    REFERENCES `PROGRAM_MULTI_PARTICIPATION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;



CREATE TABLE IF NOT EXISTS `PROGRAM_ENROLMENT_NOTIFICATIONS` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `PROGRAM_ENROLLERS_ID` BIGINT(20) NULL,
  `APPLICATION_RECEIPT` VARCHAR(45) NULL,
  `ENROLMENT_STATUS` VARCHAR(45) NULL,
  `FINAL_DECISION` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROGRAM_ENROLLER_NOTIFICATIONS_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID` ASC),
  INDEX `fk_PROGRAM_ENROLLER_NOTIFICATIONS_PROGRAM_ENROLLERS1_idx` (`PROGRAM_ENROLLERS_ID` ASC),
  CONSTRAINT `fk_PROGRAM_ENROLLER_NOTIFICATIONS_PROGRAM_PROFILE1`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROGRAM_ENROLLER_NOTIFICATIONS_PROGRAM_ENROLLERS1`
    FOREIGN KEY (`PROGRAM_ENROLLERS_ID`)
    REFERENCES `PROGRAM_ENROLLERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;



CREATE TABLE IF NOT EXISTS `PROGRAM_ENROLMENT_ATTRIBUTES` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROGRAM_ENROLMENT_ATTRIBUTES_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID` ASC),
  CONSTRAINT `fk_PROGRAM_ENROLMENT_ATTRIBUTES_PROGRAM_PROFILE1`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;



CREATE TABLE IF NOT EXISTS `PROGRAM_CUST_DATA_NOTIFICATIONS` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROGRAM_CUST_DATA_NOTIFICATIONS_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID` ASC),
  CONSTRAINT `fk_PROGRAM_CUST_DATA_NOTIFICATIONS_PROGRAM_PROFILE1`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;



CREATE TABLE IF NOT EXISTS `PROGRAM_EQUIPMENT` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` VARCHAR(55) NOT NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20) NOT NULL,
  `METER_TYPE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROGRAM_EQUIPMENT_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID` ASC),
  CONSTRAINT `fk_PROGRAM_EQUIPMENT_PROGRAM_PROFILE1`
    FOREIGN KEY (`PROGRAM_PROFILE_ID`)
    REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

ALTER TABLE ENTITY_HISTORY
ADD COLUMN `UUID` VARCHAR(55) NOT NULL;

ALTER TABLE ENTITY_HISTORY
ADD COLUMN `AUTHOR` VARCHAR(255) NULL;