//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:49:26 PM GMT 
//


package com.caiso.soa.drregistrationdata_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * An aggregated node can define a typed grouping further defined by the AnodeType enumeratuion. Types range from System Zone/Regions to Market Energy Regions to Aggregated Loads and Aggregated Generators.
 * 
 * <p>Java class for AggregateNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AggregateNode">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}IdentifiedObject_REST_mridLAP">
 *       &lt;sequence>
 *         &lt;element name="AggregatedPnode" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}AggregatedPnode"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AggregateNode", propOrder = {
    "aggregatedPnode"
})
@XmlSeeAlso({
    LoadAggregationPointDRRegistration.class
})
public class AggregateNode
    extends IdentifiedObjectRESTMridLAP
{

    @XmlElement(name = "AggregatedPnode", required = true)
    protected AggregatedPnode aggregatedPnode;

    /**
     * Gets the value of the aggregatedPnode property.
     * 
     * @return
     *     possible object is
     *     {@link AggregatedPnode }
     *     
     */
    public AggregatedPnode getAggregatedPnode() {
        return aggregatedPnode;
    }

    /**
     * Sets the value of the aggregatedPnode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregatedPnode }
     *     
     */
    public void setAggregatedPnode(AggregatedPnode value) {
        this.aggregatedPnode = value;
    }

}
