//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:49:26 PM GMT 
//


package com.caiso.soa.drregistrationdata_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Asset_Location complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Asset_Location">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}IdentifiedObjectmrid_DRR">
 *       &lt;sequence>
 *         &lt;element name="RegisteredGenerator" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}RegisteredResource_Pnode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Asset_Location", propOrder = {
    "registeredGenerator"
})
@XmlSeeAlso({
    AssetContainerLocation.class
})
public class AssetLocation
    extends IdentifiedObjectmridDRR
{

    @XmlElement(name = "RegisteredGenerator")
    protected RegisteredResourcePnode registeredGenerator;

    /**
     * Gets the value of the registeredGenerator property.
     * 
     * @return
     *     possible object is
     *     {@link RegisteredResourcePnode }
     *     
     */
    public RegisteredResourcePnode getRegisteredGenerator() {
        return registeredGenerator;
    }

    /**
     * Sets the value of the registeredGenerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegisteredResourcePnode }
     *     
     */
    public void setRegisteredGenerator(RegisteredResourcePnode value) {
        this.registeredGenerator = value;
    }

}
