//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:49:26 PM GMT 
//


package com.caiso.soa.drregistrationdata_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Asset_DRRegistration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Asset_DRRegistration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}IdentifiedObject_DRRegistration">
 *       &lt;sequence>
 *         &lt;element name="DemandResponseProvider" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}DemandResponseProvider" minOccurs="0"/>
 *         &lt;element name="DistributedActivity" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}DistributedActivity"/>
 *         &lt;element name="RegisteredGenerator" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}RegisteredResource_DRRegistration" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}Status" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Asset_DRRegistration", propOrder = {
    "demandResponseProvider",
    "distributedActivity",
    "registeredGenerator",
    "status"
})
@XmlSeeAlso({
    AssetContainerDRRegistration.class
})
public class AssetDRRegistration
    extends IdentifiedObjectDRRegistration
{

    @XmlElement(name = "DemandResponseProvider")
    protected DemandResponseProvider demandResponseProvider;
    @XmlElement(name = "DistributedActivity", required = true)
    protected DistributedActivity distributedActivity;
    @XmlElement(name = "RegisteredGenerator")
    protected RegisteredResourceDRRegistration registeredGenerator;
    protected Status status;

    /**
     * Gets the value of the demandResponseProvider property.
     * 
     * @return
     *     possible object is
     *     {@link DemandResponseProvider }
     *     
     */
    public DemandResponseProvider getDemandResponseProvider() {
        return demandResponseProvider;
    }

    /**
     * Sets the value of the demandResponseProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemandResponseProvider }
     *     
     */
    public void setDemandResponseProvider(DemandResponseProvider value) {
        this.demandResponseProvider = value;
    }

    /**
     * Gets the value of the distributedActivity property.
     * 
     * @return
     *     possible object is
     *     {@link DistributedActivity }
     *     
     */
    public DistributedActivity getDistributedActivity() {
        return distributedActivity;
    }

    /**
     * Sets the value of the distributedActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributedActivity }
     *     
     */
    public void setDistributedActivity(DistributedActivity value) {
        this.distributedActivity = value;
    }

    /**
     * Gets the value of the registeredGenerator property.
     * 
     * @return
     *     possible object is
     *     {@link RegisteredResourceDRRegistration }
     *     
     */
    public RegisteredResourceDRRegistration getRegisteredGenerator() {
        return registeredGenerator;
    }

    /**
     * Sets the value of the registeredGenerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegisteredResourceDRRegistration }
     *     
     */
    public void setRegisteredGenerator(RegisteredResourceDRRegistration value) {
        this.registeredGenerator = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

}
