//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:49:26 PM GMT 
//


package com.caiso.soa.drregistrationdata_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DistributedEnergyResourceContainer_DRRegistration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistributedEnergyResourceContainer_DRRegistration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}AssetContainer_DRRegistration">
 *       &lt;sequence>
 *         &lt;element name="terminateRegistrationFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DemandUtilityDistributionCompany" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}DemandUtilityDistributionCompany" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistributedEnergyResourceContainer_DRRegistration", propOrder = {
    "terminateRegistrationFlag",
    "demandUtilityDistributionCompany"
})
@XmlSeeAlso({
    DemandResponseRegistrationFull.class
})
public class DistributedEnergyResourceContainerDRRegistration
    extends AssetContainerDRRegistration
{

    protected Boolean terminateRegistrationFlag;
    @XmlElement(name = "DemandUtilityDistributionCompany")
    protected DemandUtilityDistributionCompany demandUtilityDistributionCompany;

    /**
     * Gets the value of the terminateRegistrationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTerminateRegistrationFlag() {
        return terminateRegistrationFlag;
    }

    /**
     * Sets the value of the terminateRegistrationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTerminateRegistrationFlag(Boolean value) {
        this.terminateRegistrationFlag = value;
    }

    /**
     * Gets the value of the demandUtilityDistributionCompany property.
     * 
     * @return
     *     possible object is
     *     {@link DemandUtilityDistributionCompany }
     *     
     */
    public DemandUtilityDistributionCompany getDemandUtilityDistributionCompany() {
        return demandUtilityDistributionCompany;
    }

    /**
     * Sets the value of the demandUtilityDistributionCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemandUtilityDistributionCompany }
     *     
     */
    public void setDemandUtilityDistributionCompany(DemandUtilityDistributionCompany value) {
        this.demandUtilityDistributionCompany = value;
    }

}
