//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:49:26 PM GMT 
//


package com.caiso.soa.drregistrationdata_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for DistributedEnergyResourceContainer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistributedEnergyResourceContainer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}AssetContainer">
 *       &lt;sequence>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="locationID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="reviewerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="terminateRegistrationFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="validLocation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DemandResponseRegistration" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}DemandResponseRegistration" minOccurs="0"/>
 *         &lt;element name="DemandUtilityDistributionCompany" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}DemandUtilityDistributionCompany" minOccurs="0"/>
 *         &lt;element name="reviewerPhoneNumber" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}TelephoneNumber" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistributedEnergyResourceContainer", propOrder = {
    "comment",
    "locationID",
    "reviewerName",
    "terminateRegistrationFlag",
    "validLocation",
    "demandResponseRegistration",
    "demandUtilityDistributionCompany",
    "reviewerPhoneNumber"
})
public class DistributedEnergyResourceContainer
    extends AssetContainer
{

    protected String comment;
    protected BigInteger locationID;
    protected String reviewerName;
    protected Boolean terminateRegistrationFlag;
    protected Boolean validLocation;
    @XmlElement(name = "DemandResponseRegistration")
    protected DemandResponseRegistration demandResponseRegistration;
    @XmlElement(name = "DemandUtilityDistributionCompany")
    protected DemandUtilityDistributionCompany demandUtilityDistributionCompany;
    protected TelephoneNumber reviewerPhoneNumber;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the locationID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocationID() {
        return locationID;
    }

    /**
     * Sets the value of the locationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocationID(BigInteger value) {
        this.locationID = value;
    }

    /**
     * Gets the value of the reviewerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewerName() {
        return reviewerName;
    }

    /**
     * Sets the value of the reviewerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewerName(String value) {
        this.reviewerName = value;
    }

    /**
     * Gets the value of the terminateRegistrationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTerminateRegistrationFlag() {
        return terminateRegistrationFlag;
    }

    /**
     * Sets the value of the terminateRegistrationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTerminateRegistrationFlag(Boolean value) {
        this.terminateRegistrationFlag = value;
    }

    /**
     * Gets the value of the validLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isValidLocation() {
        return validLocation;
    }

    /**
     * Sets the value of the validLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setValidLocation(Boolean value) {
        this.validLocation = value;
    }

    /**
     * Gets the value of the demandResponseRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link DemandResponseRegistration }
     *     
     */
    public DemandResponseRegistration getDemandResponseRegistration() {
        return demandResponseRegistration;
    }

    /**
     * Sets the value of the demandResponseRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemandResponseRegistration }
     *     
     */
    public void setDemandResponseRegistration(DemandResponseRegistration value) {
        this.demandResponseRegistration = value;
    }

    /**
     * Gets the value of the demandUtilityDistributionCompany property.
     * 
     * @return
     *     possible object is
     *     {@link DemandUtilityDistributionCompany }
     *     
     */
    public DemandUtilityDistributionCompany getDemandUtilityDistributionCompany() {
        return demandUtilityDistributionCompany;
    }

    /**
     * Sets the value of the demandUtilityDistributionCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemandUtilityDistributionCompany }
     *     
     */
    public void setDemandUtilityDistributionCompany(DemandUtilityDistributionCompany value) {
        this.demandUtilityDistributionCompany = value;
    }

    /**
     * Gets the value of the reviewerPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link TelephoneNumber }
     *     
     */
    public TelephoneNumber getReviewerPhoneNumber() {
        return reviewerPhoneNumber;
    }

    /**
     * Sets the value of the reviewerPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephoneNumber }
     *     
     */
    public void setReviewerPhoneNumber(TelephoneNumber value) {
        this.reviewerPhoneNumber = value;
    }

}
