//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:49:26 PM GMT 
//


package com.caiso.soa.drregistrationdata_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for MessagePayload complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessagePayload">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DemandResponseRegistration_Full" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}DemandResponseRegistration_Full" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DistributedEnergyResourceContainer" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}DistributedEnergyResourceContainer" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessagePayload", propOrder = {
    "demandResponseRegistrationFull",
    "distributedEnergyResourceContainer"
})
public class MessagePayload {

    @XmlElement(name = "DemandResponseRegistration_Full")
    protected List<DemandResponseRegistrationFull> demandResponseRegistrationFull;
    @XmlElement(name = "DistributedEnergyResourceContainer")
    protected List<DistributedEnergyResourceContainer> distributedEnergyResourceContainer;

    /**
     * Gets the value of the demandResponseRegistrationFull property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the demandResponseRegistrationFull property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDemandResponseRegistrationFull().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DemandResponseRegistrationFull }
     * 
     * 
     */
    public List<DemandResponseRegistrationFull> getDemandResponseRegistrationFull() {
        if (demandResponseRegistrationFull == null) {
            demandResponseRegistrationFull = new ArrayList<DemandResponseRegistrationFull>();
        }
        return this.demandResponseRegistrationFull;
    }

    /**
     * Gets the value of the distributedEnergyResourceContainer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distributedEnergyResourceContainer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistributedEnergyResourceContainer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DistributedEnergyResourceContainer }
     * 
     * 
     */
    public List<DistributedEnergyResourceContainer> getDistributedEnergyResourceContainer() {
        if (distributedEnergyResourceContainer == null) {
            distributedEnergyResourceContainer = new ArrayList<DistributedEnergyResourceContainer>();
        }
        return this.distributedEnergyResourceContainer;
    }

}
