//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:49:26 PM GMT 
//


package com.caiso.soa.drregistrationdata_v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.caiso.soa.drregistrationdata_v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DRRegistrationData_QNAME = new QName("http://www.caiso.com/soa/DRRegistrationData_v1.xsd#", "DRRegistrationData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.caiso.soa.drregistrationdata_v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DRRegistrationData }
     * 
     */
    public DRRegistrationData createDRRegistrationData() {
        return new DRRegistrationData();
    }

    /**
     * Create an instance of {@link IdentifiedObjectmridDRR }
     * 
     */
    public IdentifiedObjectmridDRR createIdentifiedObjectmridDRR() {
        return new IdentifiedObjectmridDRR();
    }

    /**
     * Create an instance of {@link IndividualPnode }
     * 
     */
    public IndividualPnode createIndividualPnode() {
        return new IndividualPnode();
    }

    /**
     * Create an instance of {@link LoadServingEntity }
     * 
     */
    public LoadServingEntity createLoadServingEntity() {
        return new LoadServingEntity();
    }

    /**
     * Create an instance of {@link AssetContainerDRR }
     * 
     */
    public AssetContainerDRR createAssetContainerDRR() {
        return new AssetContainerDRR();
    }

    /**
     * Create an instance of {@link OrganisationRoleDRP }
     * 
     */
    public OrganisationRoleDRP createOrganisationRoleDRP() {
        return new OrganisationRoleDRP();
    }

    /**
     * Create an instance of {@link TelephoneNumber }
     * 
     */
    public TelephoneNumber createTelephoneNumber() {
        return new TelephoneNumber();
    }

    /**
     * Create an instance of {@link IdentifiedObjectDRRegistration }
     * 
     */
    public IdentifiedObjectDRRegistration createIdentifiedObjectDRRegistration() {
        return new IdentifiedObjectDRRegistration();
    }

    /**
     * Create an instance of {@link RegisteredGeneratorPnode }
     * 
     */
    public RegisteredGeneratorPnode createRegisteredGeneratorPnode() {
        return new RegisteredGeneratorPnode();
    }

    /**
     * Create an instance of {@link TownDetail }
     * 
     */
    public TownDetail createTownDetail() {
        return new TownDetail();
    }

    /**
     * Create an instance of {@link LoadAggregationPoint }
     * 
     */
    public LoadAggregationPoint createLoadAggregationPoint() {
        return new LoadAggregationPoint();
    }

    /**
     * Create an instance of {@link SchedulingCoordinator }
     * 
     */
    public SchedulingCoordinator createSchedulingCoordinator() {
        return new SchedulingCoordinator();
    }

    /**
     * Create an instance of {@link Asset }
     * 
     */
    public Asset createAsset() {
        return new Asset();
    }

    /**
     * Create an instance of {@link DemandResponseRegistration }
     * 
     */
    public DemandResponseRegistration createDemandResponseRegistration() {
        return new DemandResponseRegistration();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link DemandResponseRegistrationFull }
     * 
     */
    public DemandResponseRegistrationFull createDemandResponseRegistrationFull() {
        return new DemandResponseRegistrationFull();
    }

    /**
     * Create an instance of {@link StreetDetail }
     * 
     */
    public StreetDetail createStreetDetail() {
        return new StreetDetail();
    }

    /**
     * Create an instance of {@link AggregateNode }
     * 
     */
    public AggregateNode createAggregateNode() {
        return new AggregateNode();
    }

    /**
     * Create an instance of {@link DistributedActivity }
     * 
     */
    public DistributedActivity createDistributedActivity() {
        return new DistributedActivity();
    }

    /**
     * Create an instance of {@link DistributedEnergyResourceContainerLocation }
     * 
     */
    public DistributedEnergyResourceContainerLocation createDistributedEnergyResourceContainerLocation() {
        return new DistributedEnergyResourceContainerLocation();
    }

    /**
     * Create an instance of {@link AssetContainerDRRegistration }
     * 
     */
    public AssetContainerDRRegistration createAssetContainerDRRegistration() {
        return new AssetContainerDRRegistration();
    }

    /**
     * Create an instance of {@link OrganisationRoleLSE }
     * 
     */
    public OrganisationRoleLSE createOrganisationRoleLSE() {
        return new OrganisationRoleLSE();
    }

    /**
     * Create an instance of {@link DemandResponseProvider }
     * 
     */
    public DemandResponseProvider createDemandResponseProvider() {
        return new DemandResponseProvider();
    }

    /**
     * Create an instance of {@link AssetContainerLocation }
     * 
     */
    public AssetContainerLocation createAssetContainerLocation() {
        return new AssetContainerLocation();
    }

    /**
     * Create an instance of {@link OrganisationRoleUDC }
     * 
     */
    public OrganisationRoleUDC createOrganisationRoleUDC() {
        return new OrganisationRoleUDC();
    }

    /**
     * Create an instance of {@link IdentifiedObject }
     * 
     */
    public IdentifiedObject createIdentifiedObject() {
        return new IdentifiedObject();
    }

    /**
     * Create an instance of {@link IdentifiedObjectRESTMridUDC }
     * 
     */
    public IdentifiedObjectRESTMridUDC createIdentifiedObjectRESTMridUDC() {
        return new IdentifiedObjectRESTMridUDC();
    }

    /**
     * Create an instance of {@link RegisteredResource }
     * 
     */
    public RegisteredResource createRegisteredResource() {
        return new RegisteredResource();
    }

    /**
     * Create an instance of {@link AssetDRR }
     * 
     */
    public AssetDRR createAssetDRR() {
        return new AssetDRR();
    }

    /**
     * Create an instance of {@link Pnode }
     * 
     */
    public Pnode createPnode() {
        return new Pnode();
    }

    /**
     * Create an instance of {@link DistributedEnergyResourceContainerDRR }
     * 
     */
    public DistributedEnergyResourceContainerDRR createDistributedEnergyResourceContainerDRR() {
        return new DistributedEnergyResourceContainerDRR();
    }

    /**
     * Create an instance of {@link DistributedEnergyResourceContainerDRRegistration }
     * 
     */
    public DistributedEnergyResourceContainerDRRegistration createDistributedEnergyResourceContainerDRRegistration() {
        return new DistributedEnergyResourceContainerDRRegistration();
    }

    /**
     * Create an instance of {@link AssetDRRegistration }
     * 
     */
    public AssetDRRegistration createAssetDRRegistration() {
        return new AssetDRRegistration();
    }

    /**
     * Create an instance of {@link IdentifiedObjectRESTMridLSE }
     * 
     */
    public IdentifiedObjectRESTMridLSE createIdentifiedObjectRESTMridLSE() {
        return new IdentifiedObjectRESTMridLSE();
    }

    /**
     * Create an instance of {@link DistributedEnergyResourceContainer }
     * 
     */
    public DistributedEnergyResourceContainer createDistributedEnergyResourceContainer() {
        return new DistributedEnergyResourceContainer();
    }

    /**
     * Create an instance of {@link AggregatedPnode }
     * 
     */
    public AggregatedPnode createAggregatedPnode() {
        return new AggregatedPnode();
    }

    /**
     * Create an instance of {@link DemandUtilityDistributionCompany }
     * 
     */
    public DemandUtilityDistributionCompany createDemandUtilityDistributionCompany() {
        return new DemandUtilityDistributionCompany();
    }

    /**
     * Create an instance of {@link MessagePayload }
     * 
     */
    public MessagePayload createMessagePayload() {
        return new MessagePayload();
    }

    /**
     * Create an instance of {@link Organisation }
     * 
     */
    public Organisation createOrganisation() {
        return new Organisation();
    }

    /**
     * Create an instance of {@link RegisteredResourceDRRegistration }
     * 
     */
    public RegisteredResourceDRRegistration createRegisteredResourceDRRegistration() {
        return new RegisteredResourceDRRegistration();
    }

    /**
     * Create an instance of {@link LoadAggregationPointDRRegistration }
     * 
     */
    public LoadAggregationPointDRRegistration createLoadAggregationPointDRRegistration() {
        return new LoadAggregationPointDRRegistration();
    }

    /**
     * Create an instance of {@link AssetLocation }
     * 
     */
    public AssetLocation createAssetLocation() {
        return new AssetLocation();
    }

    /**
     * Create an instance of {@link IdentifiedObjectREST37 }
     * 
     */
    public IdentifiedObjectREST37 createIdentifiedObjectREST37() {
        return new IdentifiedObjectREST37();
    }

    /**
     * Create an instance of {@link IdentifiedObjectRESTMridDRP }
     * 
     */
    public IdentifiedObjectRESTMridDRP createIdentifiedObjectRESTMridDRP() {
        return new IdentifiedObjectRESTMridDRP();
    }

    /**
     * Create an instance of {@link StreetAddress }
     * 
     */
    public StreetAddress createStreetAddress() {
        return new StreetAddress();
    }

    /**
     * Create an instance of {@link RegisteredGenerator }
     * 
     */
    public RegisteredGenerator createRegisteredGenerator() {
        return new RegisteredGenerator();
    }

    /**
     * Create an instance of {@link RegisteredResourcePnode }
     * 
     */
    public RegisteredResourcePnode createRegisteredResourcePnode() {
        return new RegisteredResourcePnode();
    }

    /**
     * Create an instance of {@link RegisteredGeneratorDRRegistration }
     * 
     */
    public RegisteredGeneratorDRRegistration createRegisteredGeneratorDRRegistration() {
        return new RegisteredGeneratorDRRegistration();
    }

    /**
     * Create an instance of {@link IdentifiedObjectRESTMridLAP }
     * 
     */
    public IdentifiedObjectRESTMridLAP createIdentifiedObjectRESTMridLAP() {
        return new IdentifiedObjectRESTMridLAP();
    }

    /**
     * Create an instance of {@link MessageHeader }
     * 
     */
    public MessageHeader createMessageHeader() {
        return new MessageHeader();
    }

    /**
     * Create an instance of {@link AssetContainer }
     * 
     */
    public AssetContainer createAssetContainer() {
        return new AssetContainer();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DRRegistrationData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.caiso.com/soa/DRRegistrationData_v1.xsd#", name = "DRRegistrationData")
    public JAXBElement<DRRegistrationData> createDRRegistrationData(DRRegistrationData value) {
        return new JAXBElement<DRRegistrationData>(_DRRegistrationData_QNAME, DRRegistrationData.class, null, value);
    }

}
