//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:49:26 PM GMT 
//


package com.caiso.soa.drregistrationdata_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Organisation that might have roles as utility, contractor, supplier, manufacturer, customer, etc.
 * 
 * <p>Java class for Organisation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Organisation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LoadServingEntity" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}LoadServingEntity"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Organisation", propOrder = {
    "loadServingEntity"
})
public class Organisation {

    @XmlElement(name = "LoadServingEntity", required = true)
    protected LoadServingEntity loadServingEntity;

    /**
     * Gets the value of the loadServingEntity property.
     * 
     * @return
     *     possible object is
     *     {@link LoadServingEntity }
     *     
     */
    public LoadServingEntity getLoadServingEntity() {
        return loadServingEntity;
    }

    /**
     * Sets the value of the loadServingEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadServingEntity }
     *     
     */
    public void setLoadServingEntity(LoadServingEntity value) {
        this.loadServingEntity = value;
    }

}
