//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:49:26 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.caiso.com/soa/DRRegistrationData_v1.xsd#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.caiso.soa.drregistrationdata_v1;
