//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:49:26 PM GMT 
//


package com.caiso.soa.drregistrationdata_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegisteredResource_DRRegistration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegisteredResource_DRRegistration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}IdentifiedObject_REST_37">
 *       &lt;sequence>
 *         &lt;element name="LoadAggregationPoint" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}LoadAggregationPoint_DRRegistration"/>
 *         &lt;element name="LoadServingEntity" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}LoadServingEntity"/>
 *         &lt;element name="SchedulingCoordinator" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}SchedulingCoordinator"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegisteredResource_DRRegistration", propOrder = {
    "loadAggregationPoint",
    "loadServingEntity",
    "schedulingCoordinator"
})
@XmlSeeAlso({
    RegisteredGeneratorDRRegistration.class
})
public class RegisteredResourceDRRegistration
    extends IdentifiedObjectREST37
{

    @XmlElement(name = "LoadAggregationPoint", required = true)
    protected LoadAggregationPointDRRegistration loadAggregationPoint;
    @XmlElement(name = "LoadServingEntity", required = true)
    protected LoadServingEntity loadServingEntity;
    @XmlElement(name = "SchedulingCoordinator", required = true)
    protected SchedulingCoordinator schedulingCoordinator;

    /**
     * Gets the value of the loadAggregationPoint property.
     * 
     * @return
     *     possible object is
     *     {@link LoadAggregationPointDRRegistration }
     *     
     */
    public LoadAggregationPointDRRegistration getLoadAggregationPoint() {
        return loadAggregationPoint;
    }

    /**
     * Sets the value of the loadAggregationPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadAggregationPointDRRegistration }
     *     
     */
    public void setLoadAggregationPoint(LoadAggregationPointDRRegistration value) {
        this.loadAggregationPoint = value;
    }

    /**
     * Gets the value of the loadServingEntity property.
     * 
     * @return
     *     possible object is
     *     {@link LoadServingEntity }
     *     
     */
    public LoadServingEntity getLoadServingEntity() {
        return loadServingEntity;
    }

    /**
     * Sets the value of the loadServingEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadServingEntity }
     *     
     */
    public void setLoadServingEntity(LoadServingEntity value) {
        this.loadServingEntity = value;
    }

    /**
     * Gets the value of the schedulingCoordinator property.
     * 
     * @return
     *     possible object is
     *     {@link SchedulingCoordinator }
     *     
     */
    public SchedulingCoordinator getSchedulingCoordinator() {
        return schedulingCoordinator;
    }

    /**
     * Sets the value of the schedulingCoordinator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchedulingCoordinator }
     *     
     */
    public void setSchedulingCoordinator(SchedulingCoordinator value) {
        this.schedulingCoordinator = value;
    }

}
