//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:49:26 PM GMT 
//


package com.caiso.soa.drregistrationdata_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A resource that is registered through the RTO participant registration system. Examples include generating unit, customer meter, and a non-physical generator or load.
 * 
 * <p>Java class for RegisteredResource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegisteredResource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndividualPnode" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}IndividualPnode" minOccurs="0"/>
 *         &lt;element name="LoadAggregationPoint" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}LoadAggregationPoint" minOccurs="0"/>
 *         &lt;element name="LoadServingEntity" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}LoadServingEntity" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegisteredResource", propOrder = {
    "individualPnode",
    "loadAggregationPoint",
    "loadServingEntity"
})
@XmlSeeAlso({
    RegisteredGenerator.class
})
public class RegisteredResource {

    @XmlElement(name = "IndividualPnode")
    protected IndividualPnode individualPnode;
    @XmlElement(name = "LoadAggregationPoint")
    protected LoadAggregationPoint loadAggregationPoint;
    @XmlElement(name = "LoadServingEntity")
    protected LoadServingEntity loadServingEntity;

    /**
     * Gets the value of the individualPnode property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualPnode }
     *     
     */
    public IndividualPnode getIndividualPnode() {
        return individualPnode;
    }

    /**
     * Sets the value of the individualPnode property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualPnode }
     *     
     */
    public void setIndividualPnode(IndividualPnode value) {
        this.individualPnode = value;
    }

    /**
     * Gets the value of the loadAggregationPoint property.
     * 
     * @return
     *     possible object is
     *     {@link LoadAggregationPoint }
     *     
     */
    public LoadAggregationPoint getLoadAggregationPoint() {
        return loadAggregationPoint;
    }

    /**
     * Sets the value of the loadAggregationPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadAggregationPoint }
     *     
     */
    public void setLoadAggregationPoint(LoadAggregationPoint value) {
        this.loadAggregationPoint = value;
    }

    /**
     * Gets the value of the loadServingEntity property.
     * 
     * @return
     *     possible object is
     *     {@link LoadServingEntity }
     *     
     */
    public LoadServingEntity getLoadServingEntity() {
        return loadServingEntity;
    }

    /**
     * Sets the value of the loadServingEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadServingEntity }
     *     
     */
    public void setLoadServingEntity(LoadServingEntity value) {
        this.loadServingEntity = value;
    }

}
