//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:49:26 PM GMT 
//


package com.caiso.soa.drregistrationdata_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * General purpose street address information.
 * 
 * <p>Java class for StreetAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StreetAddress">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="streetDetail" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}StreetDetail"/>
 *         &lt;element name="townDetail" type="{http://www.caiso.com/soa/DRRegistrationData_v1.xsd#}TownDetail"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StreetAddress", propOrder = {
    "streetDetail",
    "townDetail"
})
public class StreetAddress {

    @XmlElement(required = true)
    protected StreetDetail streetDetail;
    @XmlElement(required = true)
    protected TownDetail townDetail;

    /**
     * Gets the value of the streetDetail property.
     * 
     * @return
     *     possible object is
     *     {@link StreetDetail }
     *     
     */
    public StreetDetail getStreetDetail() {
        return streetDetail;
    }

    /**
     * Sets the value of the streetDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreetDetail }
     *     
     */
    public void setStreetDetail(StreetDetail value) {
        this.streetDetail = value;
    }

    /**
     * Gets the value of the townDetail property.
     * 
     * @return
     *     possible object is
     *     {@link TownDetail }
     *     
     */
    public TownDetail getTownDetail() {
        return townDetail;
    }

    /**
     * Sets the value of the townDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link TownDetail }
     *     
     */
    public void setTownDetail(TownDetail value) {
        this.townDetail = value;
    }

}
