

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema drcc
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS CUSTOMER_DATA(
CD_ID  BIGINT(20) NOT NULL AUTO_INCREMENT,
`SA_STATUS` VARCHAR(2) NULL,
`SERVICE_AGREEMENT_ID` VARCHAR(10) NOT NULL,
 `ACCOUNT_ID` VARCHAR(10) NOT NULL,
  `PREMISE_ID` VARCHAR(45) NOT NULL,
  `METER_ID` VARCHAR(45) NOT NULL,
  `PERSON_ID` VARCHAR(10) NOT NULL,
  `CUSTOMER_NAME` VARCHAR(100) NULL,
  `SERVICE_ADDRESS1` VARCHAR(100) NULL,
  `SERVICE_ADDRESS2` VARCHAR(100) NULL,
  `SERVICE_CITY_UPR` VARCHAR(55) NULL,
  `SERVICE_STATE` VARCHAR(2) NULL,
  `SERVICE_POSTAL` VARCHAR(12) NULL,
  `PHONE` VARCHAR(20) NULL,
  `MAILING_ADDRESS1` VARCHAR(100) NULL,
  `MAILING_ADDRESS2` VARCHAR(100) NULL,
  `MAILING_CITY_UPR` VARCHAR(55) NULL,
  `MAILING_STATE` VARCHAR(2) NULL,
  `MAILING_POSTAL` VARCHAR(12) NULL,
  `RATE_SCHEDULE` VARCHAR(10) NULL COMMENT 'RS_CD',
  `RES_YN_IND` TINYINT(1) NOT NULL DEFAULT 0,
  `SUBSTATION` VARCHAR(40) NULL, 
  `FEEDER` VARCHAR(255) NULL,
  `SERVICE_POINT_ID` VARCHAR(255) NULL COMMENT 'SP_ID', 
  `MEDICAL_BASELINE_IND` TINYINT(1) NOT NULL DEFAULT 0,
  `LIFE_SUPPORT_IND` TINYINT(1) NOT NULL DEFAULT 0,
  `SMART_RATE_IND` TINYINT(1) NOT NULL DEFAULT 0,
  `SA_SP_START_DTTM` DATETIME NULL,
  `SA_SP_STOP_DTTM` DATETIME NULL,
  `PREMISE_TYPE` VARCHAR(12) NULL,
  `SR_START_DATE` DATETIME NULL,
  `SR_END_DATE` DATETIME NULL,
  `PDP_ENROLLED` TINYINT(1) NOT NULL DEFAULT 0,
  `PDP_STATUS` VARCHAR(10) NULL,
  `PDP_START_DATE` DATETIME NULL,
  `PDP_STOP_DATE` DATETIME NULL,
  `PDP_PLAN_OPTIONS` VARCHAR(10) NULL,
  `ELEC_USAGE_NONRES` VARCHAR(15) NULL,
  `PDP_RESV_CAP_VAL` VARCHAR(12) NULL,
  `HAS_3RD_PARTY_DRP` TINYINT(1) NOT NULL DEFAULT 0,
  `PHONE_EXTENSION` VARCHAR(25) NULL,
  `SUPPLIER_IS_DRP` TINYINT(1) NOT NULL DEFAULT 0,
  `UNIQ_SA_ID` VARCHAR(11) NULL,
  `UNIQ_SA_ID_CREATE_DATE` DATETIME NULL,
  `UNIQ_SA_ID_WARN_FLAG` VARCHAR(1) NULL,
  `SA_UUID` VARCHAR(11) NULL,
  `DO_BUS_AS_NM` VARCHAR(255) NULL,
  `SA_START_DATE` DATETIME NULL,
  `SA_END_DATE` DATETIME NULL,
  `SA_NAICS` VARCHAR(17) NULL,
  `BILL_CYCLE_CD` VARCHAR(5) NULL,
  `CUST_CLASS_CD` VARCHAR(9) NULL,
  `REVENUE_CLASS_DESC` VARCHAR(41) NULL,
  `FERA_FLAG` TINYINT(1) NOT NULL DEFAULT 0 NULL,
  `BILL_SYSTEM` VARCHAR(11) NULL,
  `CUST_SIZE` VARCHAR(21) NULL,
  `MARKET_SEGMENT` VARCHAR(6) NULL,
  `CARE_FLAG` TINYINT(1) NOT NULL DEFAULT 0 NULL,
  `OPERATION_AREA` VARCHAR(61) NULL,
  `PREM_BASELINE_CHAR` VARCHAR(17) NULL,
  `MTR_BADGENBR` VARCHAR(31) NULL,
  `SM_STATUS` VARCHAR(61) NULL,
  `MTR_INSTALL_DT` DATETIME NULL,
  `MTR_UNINSTALL_DT` DATETIME NULL,
  `SM_MODULE_MFR` VARCHAR(9) NULL,
  `MTR_CONFIG_TYPE` VARCHAR(13) NULL,
  `MTR_READ_FREQ` VARCHAR(6) NULL,
  `MTR_MFG` VARCHAR(9) NULL,
  `PDP_BILL_PROTECTION` TINYINT(1) NOT NULL DEFAULT 0 NULL,
  `SR_BILL_PROTECTION` TINYINT(1) NOT NULL DEFAULT 0 NULL,
  `SA_TYPE_CD` VARCHAR(9) NULL,
  `CUSTOMER_MDMA_COMPANY_NAME` VARCHAR(257) NULL,
  `CUSTOMER_MSP_COMPANY_NAME` VARCHAR(257) NULL,
  `CUSTOMER_LSE_COMPANY_NAME` VARCHAR(257) NULL,
  `CUST_METER_READ_CYCLE12` VARCHAR(1) NULL,
  `CUST_SERVICE_VOLTAGE_CLASS` VARCHAR(13) NULL,
  `SA_SP_ID` VARCHAR(11) NULL,
  `RATE_CODE_EFFECTIVE_DATE` DATETIME NULL,
  `SERVICE_TYPE` VARCHAR(1) NULL,
  `BUSINESS_ACTIVITY_DESC` VARCHAR(255) NULL,
  `BUS_OWNER` VARCHAR(1) NULL,
  `DIVISION_CODE_19` VARCHAR(4) NULL,
  `CIRCUIT_NUMBER` VARCHAR(5) NULL,
  `SUB_STATION_NUMBER` VARCHAR(6) NULL,
  `COUNTY` VARCHAR(31) NULL,
  `CLIMATE_ZONE` VARCHAR(6) NULL,
  `ESS_DIVISION_CODE` VARCHAR(4) NULL,
  `SOURCE_SIDE_DEVICE_NUMBER` VARCHAR(26) NULL,
  `LATITUDE` VARCHAR(51) NULL,
  `LONGITUDE` VARCHAR(51) NULL,
  `TRFMR_NUMBER` VARCHAR(51) NULL,
  `TRFMR_BDG_NUMBER` VARCHAR(31) NULL,
  `ROB_CODE` VARCHAR(31) NULL,

  PRIMARY KEY (`CD_ID`)
)ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;