package com.caiso.ads.api.webservices.dispatch.v7;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-02-16T15:42:34.556Z
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://ads.caiso.com/api/webservices/dispatch/v7", name = "APIWebService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface APIWebService {

    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ads.caiso.com/api/webservices/dispatch/v7", partName = "result")
    public String getDispatchBatch(
            @WebParam(partName = "batchUID", name = "batchUID")
                    String batchUID
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ads.caiso.com/api/webservices/dispatch/v7", partName = "result")
    public int getBatchStatus(
            @WebParam(partName = "batchUID", name = "batchUID")
                    String batchUID
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ads.caiso.com/api/webservices/dispatch/v7", partName = "result")
    public String getBatchHeader(
            @WebParam(partName = "batchUID", name = "batchUID")
                    String batchUID
    );

    @WebMethod
    public void validateDispatchBatch(
            @WebParam(partName = "batchUID", name = "batchUID")
                    String batchUID
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ads.caiso.com/api/webservices/dispatch/v7", partName = "result")
    public String submitMSSLFRequest(
            @WebParam(partName = "request", name = "request")
                    String request
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ads.caiso.com/api/webservices/dispatch/v7", partName = "result")
    public String getDispatchBatchesSinceUID(
            @WebParam(partName = "batchUID", name = "batchUID")
                    String batchUID
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ads.caiso.com/api/webservices/dispatch/v7", partName = "result")
    public boolean isNewTrajData(
            @WebParam(partName = "batchUID", name = "batchUID")
                    String batchUID
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ads.caiso.com/api/webservices/dispatch/v7", partName = "result")
    public String getTrajectoryData(
            @WebParam(partName = "batchUID", name = "batchUID")
                    String batchUID
    );
}
