package com.caiso.ads.api.webservices.dispatch.v7;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-02-16T15:42:34.596Z
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "APIWebService", 
                  wsdlLocation = "file:/Users/Antonio/Downloads/ADS-ArtifactsV7_0/ADSAPIWebService.wsdl",
                  targetNamespace = "http://ads.caiso.com/api/webservices/dispatch/v7") 
public class APIWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ads.caiso.com/api/webservices/dispatch/v7", "APIWebService");
    public final static QName APIWebServicePort = new QName("http://ads.caiso.com/api/webservices/dispatch/v7", "APIWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/Antonio/Downloads/ADS-ArtifactsV7_0/ADSAPIWebService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(APIWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/Antonio/Downloads/ADS-ArtifactsV7_0/ADSAPIWebService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public APIWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public APIWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public APIWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public APIWebService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public APIWebService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public APIWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns APIWebService
     */
    @WebEndpoint(name = "APIWebServicePort")
    public APIWebService getAPIWebServicePort() {
        return super.getPort(APIWebServicePort, APIWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns APIWebService
     */
    @WebEndpoint(name = "APIWebServicePort")
    public APIWebService getAPIWebServicePort(WebServiceFeature... features) {
        return super.getPort(APIWebServicePort, APIWebService.class, features);
    }

}
