
CREATE TABLE `CHARGES_ATTRIBUTE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `RATE_PLAN_PROFILE_ID` bigint(20) NOT NULL,
  `CATEGORY` varchar(255),
  `CHARGE_OPTION`  varchar(255),
  `SERVICE_TYPE`  varchar(255),
  `EQUIPMENT_TYPE`  varchar(255),
  `WAIVEABLE` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CHARGES_ATTR_RATE_PLAN_PROFILE` FOREIGN KEY (`RATE_PLAN_PROFILE_ID`)
    REFERENCES `RATE_PLAN_PROFILE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `CHARGES_FEES` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `CHARGES_ATTRIBUTE_ID` bigint(20) NOT NULL,
  `SEASON_ID` bigint(20),
  `TIME_OF_USE` varchar(255),
  `TIME_OF_DAY_FROM` varchar(255),
  `TIME_OF_DAY_TO` varchar(255),
  `EVENT_OPTION` varchar(255),
  `FEE_TYPE` varchar(255),
  `FEE_FREQUENCY` varchar(255),
  `FEE_AMOUNT` DECIMAL(20,6),
  `FEE_UNIT` varchar(255),
  `BASELINE` varchar(255),
  `BASELINE_FROM` DECIMAL(20,6),
  `BASELINE_TO` DECIMAL(20,6),
  `BASELINE_UNIT` varchar(255),
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_FEES__CHARGES_ATTR` FOREIGN KEY (`CHARGES_ATTRIBUTE_ID`) REFERENCES `CHARGES_ATTRIBUTE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_FEES__SEASON` FOREIGN KEY (`SEASON_ID`) REFERENCES `SEASON_CALENDAR` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;