DROP TABLE IF EXISTS `RATE_CODE_PROFILE`;


CREATE TABLE IF NOT EXISTS `RATE_CODE_PROFILE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `RATE_CODE_ID` bigint(20) unsigned NOT NULL,
  `ORDER` bigint(20) ,
  `RATE_PLAN_PROFILE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_RATE_CODE_RATE_PLAN_PROFILE` FOREIGN KEY (`RATE_PLAN_PROFILE_ID`)
    REFERENCES `RATE_PLAN_PROFILE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,

  CONSTRAINT `FK_RATE_CODE_PROFILE` FOREIGN KEY (`RATE_CODE_ID`)
    REFERENCES `RATE_CODE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION

) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;