ALTER TABLE `WORK_PLAN` MODIFY COLUMN `PROGRAM_ID` bigint(20);
ALTER TABLE `WORK_PLAN` ADD COLUMN `RATE_PLAN_ID` bigint(20);
ALTER TABLE `WORK_PLAN` ADD CONSTRAINT `FK_WORK_PLAN_RATE_PLAN` FOREIGN KEY (`RATE_PLAN_ID`)
REFERENCES `RATE_PLAN` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
