CREATE TABLE `RATE_PLAN_SA_ENROLLMENT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) DEFAULT NULL,
  `SA_ID` varchar(10) NOT NULL,
  `RATE_PLAN_ID` bigint(20) NOT NULL,
  `ENROLLMENT_STATUS` varchar(255) DEFAULT NULL,
  `EFFECTIVE_START_DATE` datetime DEFAULT NULL,
  `EFFECTIVE_END_DATE` datetime DEFAULT NULL,
   PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_ENROLLMENT` (`RATE_PLAN_ID`,`SA_ID`,`EFFECTIVE_START_DATE`,`EFFECTIVE_END_DATE`),
  KEY `IDX_SA_ENROLLMENT_RATEPLAN_ID` (`RATE_PLAN_ID`),
  KEY `IDX_SA_ENROLLMENT_RATEPLAN_SA` (`SA_ID`),
  KEY `IDX_ENROLLMENT_RATEPLAN_STATUS` (`ENROLLMENT_STATUS`),
  CONSTRAINT `FK_SA_ENROLLMENT_RATE_PLAN` FOREIGN KEY (`RATE_PLAN_ID`) REFERENCES `RATE_PLAN` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `FK_SA_ENROLLMENT_RATEPLAN_SA` FOREIGN KEY (`SA_ID`) REFERENCES `SERVICE_AGREEMENT` (`SERVICE_AGREEMENT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;