DROP TABLE IF EXISTS `CREDIT_DISCOUNT`;
CREATE TABLE IF NOT EXISTS `CREDIT_DISCOUNT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `RATE_PLAN_PROFILE_ID` bigint(20) NOT NULL,
  `TYPE` varchar(255),
  `CATEGORY` varchar(255),
  `FREQUENCY` varchar(255),
  `SEASON_ID` bigint(20),
  `EQUIPMENT_TYPE`  varchar(255),
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CREDIT_DISCOUNT_RATE_PLAN_PROFILE` FOREIGN KEY (`RATE_PLAN_PROFILE_ID`)
  REFERENCES `RATE_PLAN_PROFILE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_DISCOUNT_SEASON` FOREIGN KEY (`SEASON_ID`)
  REFERENCES `SEASON_CALENDAR` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `CREDIT_DISCOUNT_FEE`;
CREATE TABLE IF NOT EXISTS `CREDIT_DISCOUNT_FEE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `CREDIT_DISCOUNT_ID` bigint(20) NOT NULL,
  `FEE_TYPE` varchar(255),
  `FEE_FREQUENCY` varchar(255),
  `FEE_AMOUNT` DECIMAL(20,6),
  `FEE_UNIT` varchar(255),
  `BASELINE` varchar(255),
  `BASELINE_FROM` DECIMAL(20,6),
  `BASELINE_TO` DECIMAL(20,6),
  `BASELINE_UNIT` varchar(255),
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CREDIT_DISCOUNT_FEE_RATE_PLAN_PROFILE` FOREIGN KEY (`CREDIT_DISCOUNT_ID`)
  REFERENCES `CREDIT_DISCOUNT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;