ALTER TABLE `RATE_PLAN_PROFILE` ADD COLUMN BILLING_TERM_FREQUENCY VARCHAR(60);
ALTER TABLE `RATE_PLAN_PROFILE` ADD COLUMN DAYS_BILLING_PERIOD_FROM INTEGER(3) NOT NULL DEFAULT '1';
ALTER TABLE `RATE_PLAN_PROFILE` ADD COLUMN DAYS_BILLING_PERIOD_TO INTEGER(3) NOT NULL DEFAULT '1';