ALTER TABLE `PLAN_INSTANCE` ADD COLUMN `TYPE` VARCHAR (40) NOT NULL DEFAULT 'PROGRAM';
ALTER TABLE `PLAN_INSTANCE` ADD COLUMN `RATE_PLAN_ID` bigint(20);
ALTER TABLE `PLAN_INSTANCE` ADD CONSTRAINT `FK_PLAN_INSTANCE_RATE` FOREIGN KEY
(`RATE_PLAN_ID`) REFERENCES `RATE_PLAN` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;




