package com.caiso.ads.api.webservices.response.v7;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-02-16T15:45:59.630Z
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://ads.caiso.com/api/webservices/response/v7", name = "APIResponseWebService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface APIResponseWebService {

    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ads.caiso.com/api/webservices/response/v7", partName = "result")
    public int declineInstruction(
            @WebParam(partName = "batchUID", name = "batchUID")
                    String batchUID,
            @WebParam(partName = "instructionUID", name = "instructionUID")
                    String instructionUID,
            @WebParam(partName = "reasonCode", name = "reasonCode")
                    int reasonCode
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ads.caiso.com/api/webservices/response/v7", partName = "result")
    public int partialAcceptInstruction(
            @WebParam(partName = "batchUID", name = "batchUID")
                    String batchUID,
            @WebParam(partName = "instructionUID", name = "instructionUID")
                    String instructionUID,
            @WebParam(partName = "acceptDOT", name = "acceptDOT")
                    double acceptDOT,
            @WebParam(partName = "reasonCode", name = "reasonCode")
                    int reasonCode
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ads.caiso.com/api/webservices/response/v7", partName = "result")
    public int acceptInstruction(
            @WebParam(partName = "batchUID", name = "batchUID")
                    String batchUID,
            @WebParam(partName = "instructionUID", name = "instructionUID")
                    String instructionUID
    );
}
