package com.itron.mdm.curtailment._2008._05;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-02-14T14:41:46.567Z
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "CurtailmentEventSave", 
                  wsdlLocation = "file:/Users/victor/Downloads/itron/CurtailmentEventSave.wsdl",
                  targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05") 
public class CurtailmentEventSave extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.itron.com/mdm/curtailment/2008/05", "CurtailmentEventSave");
    public final static QName CurtailmentEventSaveV1 = new QName("http://www.itron.com/mdm/curtailment/2008/05", "CurtailmentEventSaveV1");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/victor/Downloads/itron/CurtailmentEventSave.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CurtailmentEventSave.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/victor/Downloads/itron/CurtailmentEventSave.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CurtailmentEventSave(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CurtailmentEventSave(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurtailmentEventSave() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CurtailmentEventSave(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CurtailmentEventSave(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CurtailmentEventSave(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ICurtailmentEventSave
     */
    @WebEndpoint(name = "CurtailmentEventSaveV1")
    public ICurtailmentEventSave getCurtailmentEventSaveV1() {
        return super.getPort(CurtailmentEventSaveV1, ICurtailmentEventSave.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICurtailmentEventSave
     */
    @WebEndpoint(name = "CurtailmentEventSaveV1")
    public ICurtailmentEventSave getCurtailmentEventSaveV1(WebServiceFeature... features) {
        return super.getPort(CurtailmentEventSaveV1, ICurtailmentEventSave.class, features);
    }

}
