package com.itron.mdm.curtailment._2008._05;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * Defines the service contract for the CurtailmentEventSave service. This service defines operations allowing the creation and management of Curtailment events. The operations defined on the interface are synchronous operations.
 *
 * This class was generated by Apache CXF 3.0.4
 * 2017-02-14T14:41:46.555Z
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05", name = "ICurtailmentEventSave")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.GasObjectFactory.class, com.itron.mdm.common._2008._04.GasObjectFactory.class, GasObjectFactory.class})
public interface GasICurtailmentEventSave {

    /**
     * Manage an existing event, allowing Cancel, Close and Terminate.param: ManageEvent_Requestreturns: ManageEvent_Response
     */
    @WebMethod(operationName = "ManageEvent", action = "http://www.itron.com/mdm/curtailment/2008/05/ICurtailmentEventSave/ManageEvent")
    @Action(input = "http://www.itron.com/mdm/curtailment/2008/05/ICurtailmentEventSave/ManageEvent", output = "http://www.itron.com/mdm/curtailment/2008/05/ICurtailmentEventSave/ManageEventResponse", fault = {@FaultAction(className = GasICurtailmentEventSaveManageEventMdmServiceFaultFaultMessage.class, value = "http://www.itron.com/mdm/curtailment/2008/05/ICurtailmentEventSave/ManageEventMdmServiceFault")})
    @RequestWrapper(localName = "ManageEvent", targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05", className = "com.itron.mdm.curtailment._2008._05.ManageEvent")
    @ResponseWrapper(localName = "ManageEventResponse", targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05", className = "com.itron.mdm.curtailment._2008._05.ManageEventResponse2")
    @WebResult(name = "ManageEventResult", targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05")
    public GasManageEventResponse manageEvent(
            @WebParam(name = "request", targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05")
                    GasManageEventRequest request
    ) throws GasICurtailmentEventSaveManageEventMdmServiceFaultFaultMessage;

    @WebMethod(operationName = "ExecuteBatchSave", action = "http://www.itron.com/mdm/curtailment/2008/05/ICurtailmentEventSave/ExecuteBatchSave")
    @Action(input = "http://www.itron.com/mdm/curtailment/2008/05/ICurtailmentEventSave/ExecuteBatchSave", output = "http://www.itron.com/mdm/curtailment/2008/05/ICurtailmentEventSave/ExecuteBatchSaveResponse", fault = {@FaultAction(className = GasICurtailmentEventSaveExecuteBatchSaveMdmServiceFaultFaultMessage.class, value = "http://www.itron.com/mdm/curtailment/2008/05/ICurtailmentEventSave/ExecuteBatchSaveMdmServiceFault")})
    @RequestWrapper(localName = "ExecuteBatchSave", targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05", className = "com.itron.mdm.curtailment._2008._05.ExecuteBatchSave")
    @ResponseWrapper(localName = "ExecuteBatchSaveResponse", targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05", className = "com.itron.mdm.curtailment._2008._05.ExecuteBatchSaveResponse")
    @WebResult(name = "ExecuteBatchSaveResult", targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05")
    public GasCurtailmentEventSaveBatchGasResponse executeBatchSave(
            @WebParam(name = "request", targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05")
                    GasCurtailmentEventSaveBatchGasRequest request
    ) throws GasICurtailmentEventSaveExecuteBatchSaveMdmServiceFaultFaultMessage;

    /**
     * Create an event and issue notice to participating Service Points.returns: IssueEvent_Response
     */
    @WebMethod(operationName = "IssueEvent", action = "http://www.itron.com/mdm/curtailment/2008/05/ICurtailmentEventSave/IssueEvent")
    @Action(input = "http://www.itron.com/mdm/curtailment/2008/05/ICurtailmentEventSave/IssueEvent", output = "http://www.itron.com/mdm/curtailment/2008/05/ICurtailmentEventSave/IssueEventResponse", fault = {@FaultAction(className = GasICurtailmentEventSaveIssueEventMdmServiceFaultFaultMessage.class, value = "http://www.itron.com/mdm/curtailment/2008/05/ICurtailmentEventSave/IssueEventMdmServiceFault")})
    @RequestWrapper(localName = "IssueEvent", targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05", className = "com.itron.mdm.curtailment._2008._05.IssueEvent")
    @ResponseWrapper(localName = "IssueEventResponse", targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05", className = "com.itron.mdm.curtailment._2008._05.IssueEventResponse2")
    @WebResult(name = "IssueEventResult", targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05")
    public GasIssueEventGasResponse issueEvent(
            @WebParam(name = "request", targetNamespace = "http://www.itron.com/mdm/curtailment/2008/05")
                    GasIssueEventGasRequest request
    ) throws GasICurtailmentEventSaveIssueEventMdmServiceFaultFaultMessage;
}
