
package com.caiso.soa.retrievedrlocations_v1_wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-01-13T09:43:44.145Z
 * Generated source version: 3.0.4
 */

@WebFault(name = "StandardOutput", targetNamespace = "http://www.caiso.com/soa/StandardOutput_v1.xsd#")
public class FaultReturnType extends Exception {
    
    private com.caiso.soa.standardoutput_v1.StandardOutput standardOutput;

    public FaultReturnType() {
        super();
    }
    
    public FaultReturnType(String message) {
        super(message);
    }
    
    public FaultReturnType(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultReturnType(String message, com.caiso.soa.standardoutput_v1.StandardOutput standardOutput) {
        super(message);
        this.standardOutput = standardOutput;
    }

    public FaultReturnType(String message, com.caiso.soa.standardoutput_v1.StandardOutput standardOutput, Throwable cause) {
        super(message, cause);
        this.standardOutput = standardOutput;
    }

    public com.caiso.soa.standardoutput_v1.StandardOutput getFaultInfo() {
        return this.standardOutput;
    }
}
