package com.caiso.soa.retrievedrlocations_v1_wsdl;

import com.caiso.soa.custom.responses.RetrieveLocationsInternalResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-01-13T09:43:44.170Z
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://www.caiso.com/soa/retrieveDRLocations_v1.wsdl", name = "retrieveDRLocations_v1")
@XmlSeeAlso({com.caiso.soa._2006_06_13.standardattachmentinfor.ObjectFactory.class, com.caiso.soa.standardoutput_v1.ObjectFactory.class, com.caiso.soa.requestdrregistrationdata_v1.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT, parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RetrieveDRLocationsV1 {

    /**
     * retrieve DRLocations data
     */
    @WebMethod(operationName = "retrieveDRLocations_v1", action = "http://www.caiso.com/soa/retrieveDRLocations_v1")
    @WebResult(name = "DRLocations_attachmentResponse", targetNamespace = "http://www.caiso.com/soa/DRRegistrationData_v1.xsd", partName = "DRLocations_attachmentResponse")
    RetrieveLocationsInternalResponse retrieveDRLocationsV1(
            @WebParam(partName = "RequestDRRegistrationData", name = "RequestDRRegistrationData", targetNamespace = "http://www.caiso.com/soa/RequestDRRegistrationData_v1.xsd#")
                    com.caiso.soa.requestdrregistrationdata_v1.RequestDRRegistrationData requestData
    ) throws FaultReturnType;
}
