ALTER TABLE LR_EXCEPTION ADD COLUMN EXCEPTION_TYPE VARCHAR(50);

UPDATE LR_EXCEPTION SET EXCEPTION_TYPE = 'Location';


ALTER TABLE LR_EXCEPTION ADD COLUMN REGISTRATION_ID bigint(20) unsigned NULL;

ALTER TABLE LR_EXCEPTION DROP FOREIGN KEY LRS_STATUS_FK;

ALTER TABLE LR_EXCEPTION MODIFY COLUMN LRS_ID bigint(20) NULL;

ALTER TABLE LR_EXCEPTION ADD CONSTRAINT `LRS_STATUS_FK`
FOREIGN KEY (`LRS_ID`)
REFERENCES `LOCATION_REGISTRATION_STATUS` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

########################################################################

DROP TABLE IF EXISTS `ISO_RESOURCE`;

CREATE TABLE `ISO_RESOURCE` (
  `ID`     BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID`   VARCHAR(55)         NOT NULL,
  `SUBLAP` VARCHAR(255)        NOT NULL,
  `LSE`    VARCHAR(255)        NOT NULL,

  `TYPE`   VARCHAR(10), /*RDRR PDR*/
  `ISO_ID` BIGINT(20) UNSIGNED, /*needed for iso status*/

  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

########################################################################

DROP TABLE IF EXISTS `REGISTRATION_STATUS`;

CREATE TABLE `REGISTRATION_STATUS` (
  `ID`                  BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID`                VARCHAR(55)         NOT NULL,
  `RESOURCE_ID`         BIGINT(20) UNSIGNED NOT NULL,

  `ACTIVE_START_DATE`   DATE,
  `ACTIVE_END_DATE`     DATE,
  `ENOUGH_DAYS_METER`   VARCHAR(20), /*Success pending error in progress*/
  `REGISTRATION_STATUS` VARCHAR(20), /*Pending confirmed terminated error*/

  PRIMARY KEY (`ID`),
  CONSTRAINT `REGISTRATION_RESOURCE_FK`
  FOREIGN KEY (`RESOURCE_ID`)
  REFERENCES `ISO_RESOURCE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

########################################################################

DROP TABLE IF EXISTS `PMAX_PMIN`;

CREATE TABLE `PMAX_PMIN` (
  `ID`                   BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID`                 VARCHAR(55)         NOT NULL,
  `RESOURCE_ID`          BIGINT(20) UNSIGNED NOT NULL,

  `ESTIMATED_CAPACITY`   INT(10),
  `DISCRETE_LOAD`        TINYINT(1),
  `PMIN`                 INT(10),
  `PMAX`                 INT(10),
  `EFFECTIVE_START_DATE` DATE,
  `EFFECTIVE_END_DATE`   DATE,

  PRIMARY KEY (`ID`),
  CONSTRAINT `PMAX_PMIN_RESOURCE_FK`
  FOREIGN KEY (`RESOURCE_ID`)
  REFERENCES `ISO_RESOURCE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

########################################################################

DROP TABLE IF EXISTS `LOCATION_CHANGELOG`;

CREATE TABLE `LOCATION_CHANGELOG` (
  `ID`               BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID`             VARCHAR(55)         NOT NULL,
  `CREATION_DATE`    DATETIME,
  `EFFECTIVE_DATE`   DATETIME,
  `USER`             VARCHAR(255),
  `CHANGELOG_TYPE`   VARCHAR(55),
  `PROCESSED`        TINYINT(1)          NOT NULL DEFAULT '0',
  `LINKED_CHANGE_ID` BIGINT(20) UNSIGNED NOT NULL,
  `RESOURCE_ID`      BIGINT(20) UNSIGNED NOT NULL,
  `LOCATION_ID`      BIGINT(20)          NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `CHANGELOG_CHANGELOG_FK`
  FOREIGN KEY (`LINKED_CHANGE_ID`)
  REFERENCES `LOCATION_CHANGELOG` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CHANGELOG_LOCATION_FK`
  FOREIGN KEY (`LOCATION_ID`)
  REFERENCES `LOCATION_REGISTRATION_STATUS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CHANGELOG_RESOURCE_FK`
  FOREIGN KEY (`RESOURCE_ID`)
  REFERENCES `ISO_RESOURCE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


########################################################################

DROP TABLE IF EXISTS `LOCATION_REGISTRATION_LINKS`;

CREATE TABLE `LOCATION_REGISTRATION_LINKS` (
  `REGISTRATION_ID` bigint(20) unsigned NOT NULL,
  `LOCATION_ID` bigint(20) NOT NULL,
  CONSTRAINT `REGISTRATION_LOCATION_LINK_LOCATION_FK`
  FOREIGN KEY (`LOCATION_ID`)
  REFERENCES `LOCATION_REGISTRATION_STATUS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `REGISTRATION_LOCATION_LINK_REGISTRATION_FK`
  FOREIGN KEY (`REGISTRATION_ID`)
  REFERENCES `REGISTRATION_STATUS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;