ALTER TABLE `PROGRAM_PROFILE`
ADD COLUMN `WHOLESALE_ISO_PRODUCT_ID` bigint(20) DEFAULT NULL,
ADD CONSTRAINT `fk_MI_ISO_PROFILE_PRODUCT_ID` FOREIGN KEY (`WHOLESALE_ISO_PRODUCT_ID`)
REFERENCES `MI_ISO_PROFILE_PRODUCT` (`ID`)