ALTER TABLE SERVICE_POINT DROP COLUMN START_DATE;
ALTER TABLE SERVICE_POINT DROP COLUMN END_DATE;
DELETE FROM ENTITY_HISTORY WHERE ENTITY_NAME='ServicePoint' AND FIELD_NAME='startDate';
DELETE FROM ENTITY_HISTORY WHERE ENTITY_NAME='ServicePoint' AND FIELD_NAME='endDate';