DROP TABLE IF EXISTS `TEMP_SA_ENROLLED` ;

CREATE TABLE `TEMP_SA_ENROLLED` (
  `SAID` VARCHAR(20)
);


INSERT INTO `TEMP_SA_ENROLLED` VALUES ('7710072005');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('0045961796');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('9750653169');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('9335102940');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('9222920140');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('9928834005');

-- Resource #PGSB_1_RDRR02

INSERT INTO `TEMP_SA_ENROLLED` VALUES ('0858535806');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('0028654531');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('0030108145');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('0542353051');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('0500017237');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('0407412875');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('0279140940');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('0209171856');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('0199794031');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('1242096698');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('1245118278');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('2076307391');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('9220537785');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('9199683005');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('8770124423');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('9335102940');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('6416388613');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('6859814952');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('9425675317');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('0966427497');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('9301175455');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('9222920140');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('9750653169');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('7710072005');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('9690157792');
INSERT INTO `TEMP_SA_ENROLLED` VALUES ('8023651224');

DELIMITER $$
DROP PROCEDURE IF EXISTS insertData$$
CREATE PROCEDURE insertData()
  BEGIN


    DECLARE done INT DEFAULT FALSE;
    DECLARE AN_SA VARCHAR(20);
    DECLARE CONT INT;
    DECLARE CAPACITY_INT BIGINT(20) ;
    DECLARE CAPACITY_DEC BIGINT(20) ;
    DECLARE MEASURE_DATE DATE;
    DECLARE MEASURE_DATE_LOOP DATE;
    DECLARE SA_CURSOR CURSOR FOR SELECT `SAID`
                                 FROM `TEMP_SA_ENROLLED`;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

    SET MEASURE_DATE = '2017-04-10';
    SET CAPACITY_INT = 1000000; -- TROVE HE ARE KW H AND ARE STORED MULTIPLIED BY 1000 TO MAINTAIN PRECISION 1 MWH
    SET CAPACITY_DEC = 1001000; -- TROVE HE ARE KW H AND ARE STORED MULTIPLIED BY 1000 TO MAINTAIN PRECISION 1,001 MW H
    OPEN SA_CURSOR;

    SA_CURSOR: LOOP
      FETCH SA_CURSOR
      INTO AN_SA;

      IF DONE
      THEN LEAVE SA_CURSOR;
      END IF;
      SET CONT = 1;
      SET MEASURE_DATE_LOOP = MEASURE_DATE;

      WHILE CONT <= 20 DO

        INSERT INTO `METER_FORECAST` (`UUID`, `SERVICE_AGREEMENT_ID`, `MEASURE_TYPE`, `MEASURE_DATE`, `HOUR_END_1`, `HOUR_END_2`, `HOUR_END_3`, `HOUR_END_4`, `HOUR_END_5`,
                                      `HOUR_END_6`, `HOUR_END_7`, `HOUR_END_8`, `HOUR_END_9`, `HOUR_END_10`, `HOUR_END_11`, `HOUR_END_12`, `HOUR_END_13`, `HOUR_END_14`,
                                      `HOUR_END_15`, `HOUR_END_16`, `HOUR_END_17`, `HOUR_END_18`, `HOUR_END_19`, `HOUR_END_20`, `HOUR_END_21`, `HOUR_END_22`, `HOUR_END_23`,
                                      `HOUR_END_24`)
        VALUES
          (UUID(), AN_SA, 'ref_load', MEASURE_DATE_LOOP,
            CAPACITY_INT, cont * CAPACITY_INT, CAPACITY_INT, CAPACITY_INT,
            CAPACITY_INT, CAPACITY_INT, CAPACITY_INT, CAPACITY_INT,
            CAPACITY_INT, CAPACITY_INT, CAPACITY_INT, CAPACITY_INT,
            CAPACITY_DEC, CAPACITY_DEC, CAPACITY_DEC, CAPACITY_DEC,
            CAPACITY_DEC, CAPACITY_DEC, CAPACITY_DEC, CAPACITY_DEC,
            CAPACITY_DEC, CAPACITY_DEC, CAPACITY_DEC, CAPACITY_DEC);
        SET CONT = CONT +1;
        SET MEASURE_DATE_LOOP = MEASURE_DATE_LOOP + INTERVAL 1 DAY;

      END WHILE;

    END LOOP SA_CURSOR;

    CLOSE SA_CURSOR;
  END$$

DELIMITER ;

CALL insertData();

TRUNCATE TABLE `TEMP_SA_ENROLLED`;

DROP TABLE `TEMP_SA_ENROLLED`;

