ALTER TABLE `EVENT` ADD COLUMN `EVENT_NOTIFICATION_ID` bigint(20);

ALTER TABLE `EVENT` ADD CONSTRAINT `FK_EVENT_EVENT_NOTIFICATION`
FOREIGN KEY (`EVENT_NOTIFICATION_ID`)
REFERENCES `PDP_SR_EVENT` (`EVENT_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;