DROP TABLE IF EXISTS `EVENT_PLAN`;

CREATE TABLE IF NOT EXISTS `EVENT_PLAN` (
  `ID`   bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `NAME` varchar(55) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5650 DEFAULT CHARSET=utf8;

ALTER TABLE `EVENT` ADD COLUMN `EVENT_PLAN_ID`  bigint(20) unsigned;

ALTER TABLE `EVENT` ADD INDEX `IDX_EVENT_PLAN` (`EVENT_PLAN_ID`);