CREATE TABLE IF NOT EXISTS `ENTITY_HISTORY` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ENTITY_NAME` VARCHAR(255) NOT NULL,
  `ENTITY_ID` VARCHAR(255) NOT NULL,
  `FIELD_NAME` VARCHAR(255) NOT NULL,
  `OLD_VALUE` VARCHAR(1024) NULL,
  `NEW_VALUE` VARCHAR(1024) NULL,
  `CREATION_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CHANGE_TYPE` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `IDX_HISTORY_ENTITY_NAME` (`ENTITY_NAME` ASC),
  INDEX `IDX_HISTORY_ENTITY_ID` (`ENTITY_ID` ASC))
ENGINE = InnoDB DEFAULT CHARSET=utf8;