package com.caiso.soa.submitdrlocations_v1_wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-01-13T10:54:47.081Z
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://www.caiso.com/soa/submitDRLocations_v1.wsdl", name = "SubmitDRLocations_v1")
@XmlSeeAlso({com.caiso.soa._2006_06_13.standardattachmentinfor.ObjectFactory.class, com.caiso.soa.standardoutput_v1.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT, parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SubmitDRLocationsV1 {

    /**
     * submit DRLocations
     */
    @WebMethod(operationName = "submitDRLocations_v1", action = "http://www.caiso.com/soa/submitDRLocations_v1")
    @WebResult(name = "StandardOutput", targetNamespace = "http://www.caiso.com/soa/StandardOutput_v1.xsd#", partName = "StandardOutput")
    public com.caiso.soa.standardoutput_v1.StandardOutput submitDRLocationsV1(
            @WebParam(partName = "DRLocations_attachment", name = "DRLocations_attachment")
                    byte[] drLocationsAttachment
    ) throws FaultReturnType;
}
