ALTER TABLE `AWARD_EXCEPTION` DROP FOREIGN KEY `FK_AWARD_EXCEPTION`;
ALTER TABLE `AWARD_EXCEPTION` DROP KEY `FK_AWARD_EXCEPTION`;
ALTER TABLE `AWARD_INSTRUCTION` DROP FOREIGN KEY `FK_INSTRUCTION_DISPATCH_BATCH1`;
ALTER TABLE `AWARD_INSTRUCTION` DROP KEY `FK_INSTRUCTION_DISPATCH_BATCH1_IDX`;
ALTER TABLE `AWARD_TRAJECTORY` DROP FOREIGN KEY `TRAJECTORY_BATCH_FK`;
ALTER TABLE `AWARD_TRAJECTORY` DROP KEY `TRAJECTORY_BATCH_FK`;
ALTER TABLE `EVENT` DROP FOREIGN KEY `EVENT_BATCH_FK`;
ALTER TABLE `EVENT` DROP KEY `EVENT_BATCH_FK`;

ALTER TABLE `AWARD_EXCEPTION` DROP COLUMN `DISPATCH_BATCH_ID`;
ALTER TABLE `AWARD_INSTRUCTION` DROP COLUMN `DISPATCH_BATCH_ID`;
ALTER TABLE `AWARD_TRAJECTORY` DROP COLUMN `DISPATCH_BATCH_ID`;


ALTER TABLE EVENT DROP COLUMN DISPATCH_BATCH_ID;

DROP TABLE IF EXISTS `DISPATCH_BATCH`;