CREATE TABLE `EVENT` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `PROGRAM_ID` bigint(20) NOT NULL,
  `PROGRAM_OPTION_ID` bigint(20) DEFAULT NULL,
  `START_DATE` datetime NOT NULL,
  `END_DATE` datetime NOT NULL,
  `DISPATCH_LEVEL` varchar(50) NOT NULL DEFAULT '',
  `DISPATCH_REASON` varchar(50) NOT NULL DEFAULT '',
  `DISPATCH_STATUS` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_EVENT_PROGRAM_idx` (`PROGRAM_ID`),
  KEY `fk_EVENT_PROGRAM_OPTION_idx` (`PROGRAM_OPTION_ID`),
  CONSTRAINT `fk_EVENT_PROGRAM` FOREIGN KEY (`PROGRAM_ID`) REFERENCES `PROGRAM` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENT_PROGRAM_OPTION` FOREIGN KEY (`PROGRAM_OPTION_ID`) REFERENCES `PROGRAM_OPTION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3000 DEFAULT CHARSET=utf8;

CREATE TABLE `EVENT_DISPATCH_LEVEL` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `EVENT_ID` bigint(20) unsigned NOT NULL,
  `VALUE` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `fk_EVENT_DISPATCH_LEVEL_idx` (`EVENT_ID`),
  CONSTRAINT `fk_EVENT_DISPATCH_LEVEL` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3003 DEFAULT CHARSET=utf8;