DROP TABLE IF EXISTS `PROGRAM_ELIG_CUSTOMER_TYPE`;

CREATE TABLE `PROGRAM_ELIG_CUSTOMER_TYPE` (
  `ID` bigint(20) NOT NULL,
  `UUID` varchar(55) NOT NULL,
  `PROGRAM_PROFILE_ID` bigint(20) NOT NULL,
  `CUSTOMER_TYPE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_PR_ELIG_CUST_TYPE_PZRG_PROFILE_idx` (`PROGRAM_PROFILE_ID`),
  CONSTRAINT `fk_PR_ELIG_CUST_TYPE_PZRG_PROFILE` FOREIGN KEY (`PROGRAM_PROFILE_ID`) REFERENCES `PROGRAM_PROFILE` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;