INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Review_Split_and_Merge_records','Review Split and Merge records');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'CDW_attribute_change_notification','CDW attribute change notification notify customer (BIP only)');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'SUBlap_changes_notification','SUBlap changes notification InterACT and APX update required');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'SUBlap_changes_notification_ACT_APX','SUBlap changes notification');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Unable_to_identify_the_SUBlap','Unable to identify the SUBlap');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Profile_end_date_alert','Profile end date alert');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Eligibility_Exception_Review','Eligibility Exception Review');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'BAM_paused_alert','BAM paused alert');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Registration_Exception_Review_Reminder','Registration Exception Review Reminder');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Missing_Meter_Data_Exception_Review_reminder','Missing Meter Data Exception Review reminder');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Resource_capacity_reaching_maximum_pmax','Resource capacity reaching maximum (pmax) alert');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Resource_capacity_reaching_minimum_pmin','Resource capacity reaching minimum (pmin) alert');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Auto_Res_Mnt_off_allocate_Locations_reminder','Auto Resource Maintenance off, reminder to allocate Locations reminder');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Auto-bid_off_reminder_Bid_submission','Auto-bid off, reminder to complete Bid submission');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Auto-bid_off_deadline_approaching','Auto-bid off, Bid deadline approaching reminder (configurable on frequency)');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Review_rejected_ISO_bids_alert','Review rejected ISO bids alert');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Review_received_award_alert','Review received award (alert)');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Market_not_closed_dispatch_window_approaching','Market not closed but dispatch notification window approaching (alert)');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Dispatch_failure_manual_intervention','Dispatch failure requiring manual intervention (alert)');
INSERT INTO `NOTIFICATION_DEFINITION`(`UUID`,`TYPE`,`DESCRIPTION`) VALUES (UUID(),'Notify_non-operator_of_event_scheduled','Notify non-operator of event scheduled (i.e. CSR, etc.)');