SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `BUSINESS_OWNER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BUSINESS_OWNER` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `NAME` VARCHAR(255) NOT NULL,
  `EMAIL_LIST` TEXT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `TASK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TASK` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `TASK_TYPE` VARCHAR(5) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  `DURATION_VALUE` INT NOT NULL DEFAULT 0,
  `DURATION_MEASURE` VARCHAR(20) NOT NULL,
  `BUSINESS_OWNER_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TASK_BUSINESS_OWNER_idx` (`BUSINESS_OWNER_ID` ASC),
  CONSTRAINT `fk_TASK_BUSINESS_OWNER`
    FOREIGN KEY (`BUSINESS_OWNER_ID`)
    REFERENCES `BUSINESS_OWNER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `WORK_PLAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WORK_PLAN` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `TYPE` VARCHAR(5) NOT NULL,
  `PROGRAM_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_WORK_PLAN_PROGRAM_IDX` (`PROGRAM_ID` ASC),
  CONSTRAINT `FK_WORK_PLAN_PROGRAM`
	FOREIGN KEY (`PROGRAM_ID`)
	REFERENCES `PROGRAM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `WORK_PLAN_TASK_LIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WORK_PLAN_TASK_LIST` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `TASK_ID` BIGINT(20) NOT NULL,
  `WORK_PLAN_ID` BIGINT(20) NOT NULL,
  `ORDER` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_WORK_PLAN_TASK_LIST_TASK1_idx` (`TASK_ID` ASC),
  INDEX `fk_WORK_PLAN_TASK_LIST_WORK_PLAN1_idx` (`WORK_PLAN_ID` ASC),
  CONSTRAINT `fk_WORK_PLAN_TASK_LIST_TASK1`
    FOREIGN KEY (`TASK_ID`)
    REFERENCES `TASK` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WORK_PLAN_TASK_LIST_WORK_PLAN1`
    FOREIGN KEY (`WORK_PLAN_ID`)
    REFERENCES `WORK_PLAN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `PLAN_INSTANCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PLAN_INSTANCE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `PROGRAM_SA_ENROLLMENT_ID` BIGINT(20) NOT NULL,
  `START` DATETIME NOT NULL,
  `ESTIMATED_END` DATETIME NULL,
  `ACTUAL_END` DATETIME NULL,
  `ELAPSED_TOTAL_TIME` BIGINT(20) NULL,
  `ELAPSED_PAUSED_TIME` BIGINT(20) NULL,
  `PAUSE_START` DATETIME NULL,
  `WORK_PLAN_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_PLAN_PROGRAM_SA_ENROLLMENT_IDX` (`PROGRAM_SA_ENROLLMENT_ID` ASC),
  INDEX `fk_PLAN_INSTANCE_WORK_PLAN1_idx` (`WORK_PLAN_ID` ASC),
  CONSTRAINT `fk_PLAN_INSTANCE_WORK_PLAN1`
    FOREIGN KEY (`WORK_PLAN_ID`)
    REFERENCES `mydb`.`WORK_PLAN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PLAN_PROGRAM_SA_ENROLLMENT`
	FOREIGN KEY (`PROGRAM_SA_ENROLLMENT_ID`)
	REFERENCES `PROGRAM_SA_ENROLLMENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `TASK_INSTANCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TASK_INSTANCE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `START` DATETIME NOT NULL,
  `ESTIMATED_END` DATETIME NULL,
  `ACTUAL_END` DATETIME NULL,
  `ELAPSED_TIME` BIGINT(20) NULL,
  `WORK_PLAN_TASK_LIST_ID` BIGINT(20) NOT NULL,
  `PLAN_INSTANCE_ID` BIGINT(20) NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  `NOTES` TEXT NULL,
  `LAST_UPDATED` DATETIME NULL,
  `REFERENCE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TASK_TRACKER_WORK_PLAN_TASK_LIST1_idx` (`WORK_PLAN_TASK_LIST_ID` ASC),
  INDEX `fk_TASK_INSTANCE_PLAN_INSTANCE1_idx` (`PLAN_INSTANCE_ID` ASC),
  CONSTRAINT `fk_TASK_TRACKER_WORK_PLAN_TASK_LIST1`
    FOREIGN KEY (`WORK_PLAN_TASK_LIST_ID`)
    REFERENCES `WORK_PLAN_TASK_LIST` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TASK_INSTANCE_PLAN_INSTANCE1`
    FOREIGN KEY (`PLAN_INSTANCE_ID`)
    REFERENCES `PLAN_INSTANCE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `NOTIFICATION_DEFINITION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NOTIFICATION_DEFINITION` (
  `ID` BIGINT(20) NOT NULL,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `TYPE` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  `BUSINESS_OWNER_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_NOTIFICATION_DEFINITION_BUSINESS_OWNER1_idx` (`BUSINESS_OWNER_ID` ASC),
  CONSTRAINT `fk_NOTIFICATION_DEFINITION_BUSINESS_OWNER1`
    FOREIGN KEY (`BUSINESS_OWNER_ID`)
    REFERENCES `BUSINESS_OWNER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `NOTIFICATION_INSTANCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NOTIFICATION_INSTANCE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `NOTIFICATION_DEFINITION_ID` BIGINT(20) NOT NULL,
  `BUSINESS_OWNER_ID` BIGINT(20) NOT NULL,
  `CREATED` DATETIME NOT NULL,
  `CLOSED` DATETIME NULL,
  `REFERENCE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_NOTIFICATION_INSTANCE_NOTIFICATION_DEFINITION1_idx` (`NOTIFICATION_DEFINITION_ID` ASC),
  INDEX `fk_NOTIFICATION_INSTANCE_BUSINESS_OWNER1_idx` (`BUSINESS_OWNER_ID` ASC),
  CONSTRAINT `fk_NOTIFICATION_INSTANCE_NOTIFICATION_DEFINITION1`
    FOREIGN KEY (`NOTIFICATION_DEFINITION_ID`)
    REFERENCES `NOTIFICATION_DEFINITION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTIFICATION_INSTANCE_BUSINESS_OWNER1`
    FOREIGN KEY (`BUSINESS_OWNER_ID`)
    REFERENCES `BUSINESS_OWNER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
