CREATE TABLE `AWARD_INSTRUCTION_DETAIL` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) DEFAULT NULL,
  `INSTRUCTION_ID` bigint(20) unsigned NOT NULL,
  `SERVICE_TYPE` varchar(55) DEFAULT NULL,
  `ISO_SEQ` int(10) NOT NULL,
  `CAPACITY` bigint(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `AWARD_INSTRUCTION_DETAIL_FK` (`INSTRUCTION_ID`),
  CONSTRAINT `AWARD_INSTRUCTION_DETAIL_FK` FOREIGN KEY (`INSTRUCTION_ID`) REFERENCES `AWARD_INSTRUCTION` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;