DROP TABLE IF EXISTS `SUBLAP_PROGRAM_MAPPING`;

CREATE TABLE `SUBLAP_PROGRAM_MAPPING` (
  `ID` bigint(20) NOT NULL,
  `UUID` varchar(55) NOT NULL,
  `PROGRAM_PROFILE_ID` bigint(20) NOT NULL,
  `SUBLAP_CODE` varchar(5) NOT NULL DEFAULT '',
  `DRMS_PROGRAM_ID` varchar(55) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_SUBLAP_PROGRAM_MAPPING_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID`),
  KEY `fk_SUBLAP_PROGRAM_MAPPING_SUBLAP1` (`SUBLAP_CODE`),
  CONSTRAINT `fk_SUBLAP_PROGRAM_MAPPING_PROGRAM_PROFILE1` FOREIGN KEY (`PROGRAM_PROFILE_ID`) REFERENCES `PROGRAM_PROFILE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUBLAP_PROGRAM_MAPPING_SUBLAP1` FOREIGN KEY (`SUBLAP_CODE`) REFERENCES `SUBLAP` (`CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;