DROP TABLE IF EXISTS `IMPACTED_CUSTOMER`;

CREATE TABLE `IMPACTED_CUSTOMER` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `EVENT_ID` bigint(20) unsigned NOT NULL,
  `LOCATION_SUBMISSION_STATUS_ID` bigint(20) NOT NULL,
  `DRMS_ID` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `IMPACTED_CUSTOMER_EVENT_FK` (`EVENT_ID`),
  KEY `IMPACTED_CUSTOMER_LOCATION_FK` (`LOCATION_SUBMISSION_STATUS_ID`),
  CONSTRAINT `IMPACTED_CUSTOMER_EVENT_FK` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `IMPACTED_CUSTOMER_LOCATION_FK` FOREIGN KEY (`LOCATION_SUBMISSION_STATUS_ID`) REFERENCES `LOCATION_SUBMISSION_STATUS` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3332 DEFAULT CHARSET=utf8;