CREATE TABLE `PROGRAM_DEFINED_DISPATCH_LEVEL` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `DISPATCH_LEVEL` varchar(50) NOT NULL,
  `PROGRAM_PROFILE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PDDL_PROFILE` (`PROGRAM_PROFILE_ID`),
  CONSTRAINT `FK_PDDL_PROFILE` FOREIGN KEY (`PROGRAM_PROFILE_ID`) REFERENCES `PROGRAM_PROFILE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2844 DEFAULT CHARSET=utf8;

CREATE TABLE `PROGRAM_EVENT_DURATION` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `PROGRAM_PROFILE_ID` bigint(20) NOT NULL,
  `EVENT_DURATION_OPTION` varchar(50) DEFAULT NULL,
  `MIN_DURATION` smallint(3) DEFAULT NULL,
  `MAX_DURATION` smallint(3) DEFAULT NULL,
  `MIN_DURATION_UNITS` varchar(50) NOT NULL,
  `MAX_DURATION_UNITS` varchar(50) NOT NULL,
  `MAX_EVENT_HOURS_PER_YEAR` smallint(3) DEFAULT NULL,
  `MAX_EVENT_HOURS_PER_MONTH` smallint(3) DEFAULT NULL,
  `MAX_EVENT_HOURS_PER_DAY` smallint(3) DEFAULT NULL,
  `MIN_LEAD_TIME_TO_SHED_LOAD` smallint(3) DEFAULT NULL,
  `MIN_LEAD_TIME_TO_SHED_LOAD_UNITS` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PED_PROFILE` (`PROGRAM_PROFILE_ID`),
  CONSTRAINT `FK_PED_PROFILE` FOREIGN KEY (`PROGRAM_PROFILE_ID`) REFERENCES `PROGRAM_PROFILE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2826 DEFAULT CHARSET=utf8;

CREATE TABLE `PROGRAM_DEFINED_DISPATCH_REASON` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `DISPATCH_REASON` varchar(50) NOT NULL,
  `PROGRAM_PROFILE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PDDR_PROFILE` (`PROGRAM_PROFILE_ID`),
  CONSTRAINT `FK_PDDR_PROFILE` FOREIGN KEY (`PROGRAM_PROFILE_ID`) REFERENCES `PROGRAM_PROFILE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2849 DEFAULT CHARSET=utf8;

CREATE TABLE `PROGRAM_CUSTOMER_NOTIFICATION` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `PROGRAM_PROFILE_ID` bigint(20) NOT NULL,
  `NOTIFICATION_LEAD_TIME` smallint(3) DEFAULT NULL,
  `NOTIFICATION_LEAD_TIME_UNITS` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PNC_PROFILE` (`PROGRAM_PROFILE_ID`),
  CONSTRAINT `FK_PNC_PROFILE` FOREIGN KEY (`PROGRAM_PROFILE_ID`) REFERENCES `PROGRAM_PROFILE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2856 DEFAULT CHARSET=utf8;