DROP TABLE IF EXISTS `SAFETY_REDUCTION_FACTOR`;

CREATE TABLE IF NOT EXISTS `SAFETY_REDUCTION_FACTOR` (
  `ID`                 BIGINT(20)  NOT NULL,
  `UUID`               VARCHAR(55) NULL,
  `HOUR_END`           INT(2)      NOT NULL,
  `PROGRAM_HOLIDAY`    BIGINT(10)  NULL,
  `MONDAY`             BIGINT(10)  NULL,
  `TUESDAY`            BIGINT(10)  NULL,
  `WEDNESDAY`          BIGINT(10)  NULL,
  `THURSDAY`           BIGINT(10)  NULL,
  `FRIDAY`             BIGINT(10)  NULL,
  `SATURDAY`           BIGINT(10)  NULL,
  `SUNDAY`             BIGINT(10)  NULL,
  `PROGRAM_PROFILE_ID` BIGINT(20)  NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_SRF_PROGRAM_PROFILE`
  FOREIGN KEY (`PROGRAM_PROFILE_ID`)
  REFERENCES `PROGRAM_PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

ALTER TABLE PROGRAM_PROFILE ADD COLUMN `DEFAULT_BID_PRICE` BIGINT(16);
ALTER TABLE PROGRAM_PROFILE ADD COLUMN `DUAL_EVENT_BID_PRICE` BIGINT(16);
ALTER TABLE PROGRAM_PROFILE ADD COLUMN `CUSTOMER_FATIGUE_THRESHOLD` BIGINT(10);
ALTER TABLE PROGRAM_PROFILE ADD COLUMN `CONSECUTIVE_DISPATCH_DAYS` INT(10);