DROP TABLE `INSTRUCTION_BID_LINK`;
ALTER TABLE `AWARD_INSTRUCTION` ADD COLUMN   `BID_ID`         BIGINT(20) UNSIGNED NOT NULL;
ALTER TABLE `AWARD_INSTRUCTION` ADD COLUMN   `EVENT_ID`         BIGINT(20) UNSIGNED;
ALTER TABLE `EVENT` DROP FOREIGN KEY `FK_INSTRUCTION`;
ALTER TABLE `EVENT` DROP COLUMN `INSTRUCTION_ID`;
ALTER TABLE `AWARD_INSTRUCTION` ADD CONSTRAINT `FK_INSTRUCTION` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION



