CREATE TABLE `EVENT_ENROLLMENT_LINKS` (
  `EVENT_ID` bigint(20) unsigned NOT NULL,
  `ENROLLMENT_ID` bigint(20) NOT NULL,
  CONSTRAINT `EVENT_ENROLLMENT_LINK_EVENT_FK`
  FOREIGN KEY (`EVENT_ID`)
  REFERENCES `EVENT` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `EVENT_ENROLLMENT_LINK_ENROLLMENT_FK`
  FOREIGN KEY (`ENROLLMENT_ID`)
  REFERENCES `PROGRAM_SA_ENROLLMENT` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
