CREATE TABLE `TEMPERATURE_FORECAST` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `DEGREES` DECIMAL(6,2) NOT NULL,
  `DAY` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY uq_day_forecast (`DAY`)
  ) ENGINE=InnoDB AUTO_INCREMENT=2826 DEFAULT CHARSET=utf8;
