ALTER TABLE MI_ISO_PROFILE_PRODUCT ADD COLUMN DISPATCH_TYPE VARCHAR(20);
ALTER TABLE MI_ISO_PROFILE_PRODUCT ADD COLUMN MAX_RESOURCE_SIZE_VALUE NUMERIC(10,3);
ALTER TABLE MI_ISO_PROFILE_PRODUCT ADD COLUMN MAX_RESOURCE_SIZE_UNIT VARCHAR(5);
ALTER TABLE MI_ISO_PROFILE_PRODUCT ADD COLUMN CURTAILMENT_RESPONSE_TIME_VALUE INTEGER(10);
ALTER TABLE MI_ISO_PROFILE_PRODUCT ADD COLUMN CURTAILMENT_RESPONSE_TIME_UNIT VARCHAR(20);