CREATE TABLE `DRMS_PROGRAM_MAPPING` (
  `ID` bigint(20) NOT NULL,
  `UUID` varchar(55) NOT NULL,
  `PROGRAM_PROFILE_ID` bigint(20) NOT NULL,
  `DISPATCH_LEVEL` varchar(55) DEFAULT NULL,
  `DISPATCH_REASON` varchar(55) DEFAULT NULL,
  `DRMS_PROGRAM_ID` varchar(55) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_DRMS_PROGRAM_MAPPING_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID`),
  CONSTRAINT `fk_DRMS_PROGRAM_MAPPING_PROGRAM_PROFILE1` FOREIGN KEY (`PROGRAM_PROFILE_ID`) REFERENCES `PROGRAM_PROFILE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SUBLAP_PROGRAM_MAPPING` (
  `ID` bigint(20) NOT NULL,
  `UUID` varchar(55) NOT NULL,
  `PROGRAM_PROFILE_ID` bigint(20) NOT NULL,
  `SUBLAP_ID` bigint(20) unsigned NOT NULL,
  `DRMS_PROGRAM_ID` varchar(55) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_SUBLAP_PROGRAM_MAPPING_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID`),
  KEY `fk_SUBLAP_PROGRAM_MAPPING_SUBLAP1` (`SUBLAP_ID`),
  CONSTRAINT `fk_SUBLAP_PROGRAM_MAPPING_PROGRAM_PROFILE1` FOREIGN KEY (`PROGRAM_PROFILE_ID`) REFERENCES `PROGRAM_PROFILE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUBLAP_PROGRAM_MAPPING_SUBLAP1` FOREIGN KEY (`SUBLAP_ID`) REFERENCES `SUBLAP` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;