ALTER TABLE `PROGRAM_PROFILE` DROP COLUMN `ESSENTIAL_CUST_ROTATING_BLOCK`;
ALTER TABLE `PROGRAM_PROFILE` DROP COLUMN `SERVICE_LEVEL_COMMITMENT`;
ALTER TABLE `PROGRAM_PROFILE` ADD COLUMN `FSL_TIME_HORIZON` int(11) DEFAULT NULL;

CREATE TABLE `PROGRAM_ESSENTIAL_CUSTOMER` (
  `ID` bigint(20) NOT NULL,
  `UUID` varchar(55) NOT NULL,
  `PROGRAM_PROFILE_ID` bigint(20) NOT NULL,
  `ESSENTIAL_CUSTOMER` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PROGRAM_ESSENTIAL_CUSTOMER_PROGRAM_PROFILE1_idx` (`PROGRAM_PROFILE_ID`),
  CONSTRAINT `fk_PROGRAM_ESSENTIAL_CUSTOMER_PROGRAM_PROFILE1` FOREIGN KEY (`PROGRAM_PROFILE_ID`) REFERENCES `PROGRAM_PROFILE` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;