ALTER TABLE `ISO_OUTAGE` DROP COLUMN DATE;
ALTER TABLE `ISO_OUTAGE` ADD COLUMN `IMPACTED_RESOURCE_ID` bigint(20) unsigned NOT NULL;
ALTER TABLE `ISO_OUTAGE` ADD CONSTRAINT `fk_ISO_OUTAGE_IMPACTED_RESOURCE` FOREIGN KEY (`IMPACTED_RESOURCE_ID`) REFERENCES `IMPACTED_RESOURCE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;