DROP TABLE IF EXISTS `FILE_PROCESSOR_ERRORS`;

DROP TABLE IF EXISTS `FILE_PROCESSOR_LOG`;

CREATE TABLE `drcc`.`FILE_PROCESSOR_LOG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `PROCESS_DATE` DATETIME NULL,
  `FILENAME` VARCHAR(255) NULL,
  `TIME_COMPLETED` DATETIME NULL,
  `ERRORS` TINYINT(1) DEFAULT 0, -- O NO ERRORS, 1 ERRORS
  PRIMARY KEY (`ID`)
  )
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

CREATE TABLE `drcc`.`FILE_PROCESSOR_ERRORS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL,
  `ROWDATA` BLOB NULL,
  `ERROR` VARCHAR(255) NULL,
  `EXCEPTION_DETAIL` BLOB NULL,
  `RESOLVED` TINYINT(1) DEFAULT 0, -- 0 NOT RESOLVED 1 RESOLVED
  `FILE_PROCESSOR_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT FP_ERRORS_FK FOREIGN KEY (`FILE_PROCESSOR_ID`) REFERENCES `FILE_PROCESSOR_LOG` (`ID`)
  ) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;