
DROP TABLE IF EXISTS `INSTRUCTION_BID_LINK`;
DROP TABLE IF EXISTS `AWARD_INSTRUCTION`;
DROP TABLE IF EXISTS `DISPATCH_BATCH`;

CREATE TABLE IF NOT EXISTS `DISPATCH_BATCH` (
  `ID`               BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID`             VARCHAR(55) NULL,
  `BATCH_ID`         VARCHAR(45) NULL,
  `MARKET_ID`        VARCHAR(45) NULL,
  `STATUS`           INTEGER(10)  NULL,
  `RECEIVED`         DATETIME    NULL,
  `SENT`             DATETIME    NULL,
  `EXPIRES`          DATETIME    NULL,
  `TYPE`             INTEGER(10)  NULL,
  `START_TIME`       DATETIME    NULL,
  `DISPATCH_MODE`    INTEGER(10)  NULL,
  `BINDING_FLAG`     VARCHAR(1)  NULL,
  `REVISION_NUMBER`  INTEGER(10)  NULL,
  `CONTINGENCY_TYPE` VARCHAR(45) NULL,
  `PATH_EXCLUSION`   VARCHAR(45) NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `AWARD_INSTRUCTION` (
  `ID`                       BIGINT(20) UNSIGNED  NOT NULL AUTO_INCREMENT,
  `UUID`                     VARCHAR(55)  NULL,
  `DISPATCH_BATCH_ID`        BIGINT(20)  UNSIGNED NOT NULL,
  `STATUS_CODE`              VARCHAR(45)  NULL,
  `CAPACITY_HE1`             BIGINT(10)   NULL,
  `PRICE_HE1`                BIGINT(16)   NULL,
  `CAPACITY_HE2`             BIGINT(10)   NULL,
  `PRICE_HE2`                BIGINT(16)   NULL,
  `CAPACITY_HE3`             BIGINT(10)   NULL,
  `PRICE_HE3`                BIGINT(16)   NULL,
  `CAPACITY_HE4`             BIGINT(10)   NULL,
  `PRICE_HE4`                BIGINT(16)   NULL,
  `CAPACITY_HE5`             BIGINT(10)   NULL,
  `PRICE_HE5`                BIGINT(16)   NULL,
  `CAPACITY_HE6`             BIGINT(10)   NULL,
  `PRICE_HE6`                BIGINT(16)   NULL,
  `CAPACITY_HE7`             BIGINT(10)   NULL,
  `PRICE_HE7`                BIGINT(16)   NULL,
  `CAPACITY_HE8`             BIGINT(10)   NULL,
  `PRICE_HE8`                BIGINT(16)   NULL,
  `CAPACITY_HE9`             BIGINT(10)   NULL,
  `PRICE_HE9`                BIGINT(16)   NULL,
  `CAPACITY_HE10`            BIGINT(10)   NULL,
  `PRICE_HE10`               BIGINT(16)   NULL,
  `CAPACITY_HE11`            BIGINT(10)   NULL,
  `PRICE_HE11`               BIGINT(16)   NULL,
  `CAPACITY_HE12`            BIGINT(10)   NULL,
  `PRICE_HE12`               BIGINT(16)   NULL,
  `CAPACITY_HE13`            BIGINT(10)   NULL,
  `PRICE_HE13`               BIGINT(16)   NULL,
  `CAPACITY_HE14`            BIGINT(10)   NULL,
  `PRICE_HE14`               BIGINT(16)   NULL,
  `CAPACITY_HE15`            BIGINT(10)   NULL,
  `PRICE_HE15`               BIGINT(16)   NULL,
  `CAPACITY_HE16`            BIGINT(10)   NULL,
  `PRICE_HE16`               BIGINT(16)   NULL,
  `CAPACITY_HE17`            BIGINT(10)   NULL,
  `PRICE_HE17`               BIGINT(16)   NULL,
  `CAPACITY_HE18`            BIGINT(10)   NULL,
  `PRICE_HE18`               BIGINT(16)   NULL,
  `CAPACITY_HE19`            BIGINT(10)   NULL,
  `PRICE_HE19`               BIGINT(16)   NULL,
  `CAPACITY_HE20`            BIGINT(10)   NULL,
  `PRICE_HE20`               BIGINT(16)   NULL,
  `CAPACITY_HE21`            BIGINT(10)   NULL,
  `PRICE_HE21`               BIGINT(16)   NULL,
  `CAPACITY_HE22`            BIGINT(10)   NULL,
  `PRICE_HE22`               BIGINT(16)   NULL,
  `CAPACITY_HE23`            BIGINT(10)   NULL,
  `PRICE_HE23`               BIGINT(16)   NULL,
  `CAPACITY_HE24`            BIGINT(10)   NULL,
  `PRICE_HE24`               BIGINT(16)   NULL,
  `RETAIL_DISPATCH_SCH_TYPE` VARCHAR(45)  NULL,
  `RESOURCE_ID`              BIGINT(20) UNSIGNED NOT NULL,
  `CONFIGURATION_ID`         VARCHAR(45)  NULL,
  `START_TIME`               DATETIME     NULL,
  `END_TIME`                 DATETIME     NULL,
  `DOT`                      VARCHAR(45)  NULL,
  `TYPE`                     INTEGER (10)  NULL,
  `AGC_FLAG`                 VARCHAR(1)   NULL,
  `RMR_FLAG`                 VARCHAR(1)   NULL,
  `VALIDATED`                DATETIME     NULL,
  `VALIDATED_BY`             VARCHAR(255) NULL,
  `API_VALIDATED`            DATETIME     NULL,
  `API_VALIDATED_BY`         VARCHAR(255) NULL,
  `REVISION_NUMBER`          INTEGER(10)   NULL,
  `BID_DELAY`                INTEGER(10)   NULL,
  `ISO_START_TIME`           DATETIME     NULL,
  `DISPATCH_PROGRESS`        VARCHAR(1)   NULL,
  `DISPUTE_STATUS`           VARCHAR(45)  NULL,
  `ISO_ID`                   VARCHAR(45)  NULL,
  `ISO_RESOURCE_ID`          VARCHAR(45)  NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_INSTRUCTION_DISPATCH_BATCH1_IDX` (`DISPATCH_BATCH_ID` ASC),
  CONSTRAINT `FK_INSTRUCTION_DISPATCH_BATCH1`
  FOREIGN KEY (`DISPATCH_BATCH_ID`)
  REFERENCES `DISPATCH_BATCH` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `FK_ISORESOURCE_IDX` (`DISPATCH_BATCH_ID` ASC),
  CONSTRAINT `FK_ISORESOURCE`
  FOREIGN KEY (`RESOURCE_ID`)
  REFERENCES `ISO_RESOURCE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `INSTRUCTION_BID_LINK` (
  `INSTRUCTION_ID` BIGINT(20) UNSIGNED NOT NULL,
  `BID_ID`         BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`INSTRUCTION_ID`, `BID_ID`),
  INDEX `FK_INSTRUCTION_HAS_BID_BID1_IDX` (`BID_ID` ASC),
  INDEX `FK_INSTRUCTION_HAS_BID_INSTRUCTION1_IDX` (`INSTRUCTION_ID` ASC),
  CONSTRAINT `FK_INSTRUCTION_HAS_BID_INSTRUCTION1`
  FOREIGN KEY (`INSTRUCTION_ID`)
  REFERENCES `AWARD_INSTRUCTION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_INSTRUCTION_HAS_BID_BID1`
  FOREIGN KEY (`BID_ID`)
  REFERENCES `BID` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

ALTER TABLE EVENT ADD COLUMN `INSTRUCTION_ID` BIGINT(20) UNSIGNED;
ALTER TABLE EVENT ADD CONSTRAINT `FK_INSTRUCTION` FOREIGN KEY (`INSTRUCTION_ID`) REFERENCES `AWARD_INSTRUCTION`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;