ALTER TABLE BID ADD COLUMN RESOURCE_ID BIGINT(20) UNSIGNED NULL;
UPDATE BID b join REGISTRATION_STATUS r ON b.REGISTRATION_STATUS_ID = r.ID SET b.RESOURCE_ID = r.RESOURCE_ID;
ALTER TABLE BID MODIFY COLUMN RESOURCE_ID BIGINT(20) UNSIGNED NOT NULL;
ALTER TABLE BID ADD CONSTRAINT FK_BID_RESOURCE FOREIGN KEY (`RESOURCE_ID`) REFERENCES `ISO_RESOURCE` (`ID`);
ALTER TABLE BID DROP INDEX unique_bid;
ALTER TABLE BID ADD CONSTRAINT unique_bid UNIQUE(TRADE_DATE,RESOURCE_ID);
ALTER TABLE BID DROP FOREIGN KEY fk_SEGMENT_REGISTRATION_STATUS;
ALTER TABLE BID DROP COLUMN REGISTRATION_STATUS_ID;

