DROP TABLE IF EXISTS `AWARD`;

CREATE TABLE IF NOT EXISTS `AWARD` (
  `ID`          BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UUID`        VARCHAR(55)         NULL,
  `TRADE_DATE`  DATE                NOT NULL,
  `START_TIME`  DATETIME            NULL,
  `END_TIME`    DATETIME            NULL,
  `RESOURCE_ID` BIGINT(20) UNSIGNED NOT NULL,
  `EVENT_ID`    BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_EVENT_AWARD`
  FOREIGN KEY (`EVENT_ID`)
  REFERENCES `EVENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

ALTER TABLE `AWARD_INSTRUCTION`
  ADD COLUMN `AWARD_ID` BIGINT(20) UNSIGNED NOT NULL;
ALTER TABLE `AWARD_TRAJECTORY`
  ADD COLUMN `AWARD_ID` BIGINT(20) UNSIGNED NOT NULL;
ALTER TABLE `AWARD_EXCEPTION`
  ADD COLUMN `AWARD_ID` BIGINT(20) UNSIGNED NOT NULL;

ALTER TABLE `AWARD_INSTRUCTION`
  ADD CONSTRAINT `FK_INSTRUCTION_AWARD`
FOREIGN KEY (`AWARD_ID`)
REFERENCES `AWARD` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `AWARD_TRAJECTORY`
  ADD CONSTRAINT `FK_TRAJECTORY_AWARD`
FOREIGN KEY (`AWARD_ID`)
REFERENCES `AWARD` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `AWARD_EXCEPTION`
  ADD CONSTRAINT `FK_EXCEPTION_AWARD`
FOREIGN KEY (`AWARD_ID`)
REFERENCES `AWARD` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


