CREATE TABLE `LAYER7_PEAK_DEMAND_HISTORY` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UUID` varchar(55) NOT NULL DEFAULT '',
  `SERVICE_AGREEMENT_ID` varchar(10) NOT NULL DEFAULT '',
  `MONTH_YEAR` varchar(20) NOT NULL DEFAULT '',
  `MAX_KW_DEMAND` varchar(20) NOT NULL DEFAULT '',
  `SUMMER_ON_PEAK_KW` varchar(20) NOT NULL DEFAULT '',
  `SUMMER_ON_PEAK_KW_H` varchar(20) NOT NULL DEFAULT '',
  `WINTER_PARTIAL_PEAK_KW` varchar(20) NOT NULL DEFAULT '',
  `WINTER_PARTIAL_PEAK_KW_H` varchar(20) NOT NULL DEFAULT '',
  `SUMMER_ON_PEAK_HOURS` varchar(20) NOT NULL DEFAULT '',
  `WINTER_PARTIAL_PEAK_HOURS` varchar(20) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_L7PDH_SERVICE_AGREEMENT`
    FOREIGN KEY (`SERVICE_AGREEMENT_ID`)
    REFERENCES `SERVICE_AGREEMENT` (`SERVICE_AGREEMENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;