CREATE TABLE `ISO_OUTAGE` (
  `ID` bigint(20) NOT NULL,
  `UUID` varchar(55) NOT NULL,
  `RESOURCE_ID` bigint(20) unsigned NOT NULL,
  `DATE` datetime NOT NULL,
  `OUTAGE_ID` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `RESOURCE_ID` (`RESOURCE_ID`,`DATE`),
  KEY `fk_ISO_OUTAGE_RESOURCE_idx` (`RESOURCE_ID`),
  CONSTRAINT `fk_ISO_OUTAGE_RESOURCE` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `ISO_RESOURCE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;