UPDATE MI_ISO_PROFILE_PRODUCT SET BID_SUBMISSION_SC_ON='TRADE_DAY' WHERE BID_SUBMISSION_SC_ON LIKE 'Trade Day';
UPDATE MI_ISO_PROFILE_PRODUCT SET BID_SUBMISSION_ISO_ON='TRADE_DAY' WHERE BID_SUBMISSION_ISO_ON LIKE 'Trade Day';
UPDATE MI_ISO_PROFILE_PRODUCT SET AUTO_BID_LOW_RISK_ON='TRADE_DAY' WHERE AUTO_BID_LOW_RISK_ON LIKE 'Trade Day';
UPDATE MI_ISO_PROFILE_PRODUCT SET BID_SUBMISSION_SC_ON='TRADE_DAY_MINUS_ONE' WHERE BID_SUBMISSION_SC_ON LIKE 'Trade Day - 1';
UPDATE MI_ISO_PROFILE_PRODUCT SET BID_SUBMISSION_ISO_ON='TRADE_DAY_MINUS_ONE' WHERE BID_SUBMISSION_ISO_ON LIKE 'Trade Day - 1';
UPDATE MI_ISO_PROFILE_PRODUCT SET AUTO_BID_LOW_RISK_ON='TRADE_DAY_MINUS_ONE' WHERE AUTO_BID_LOW_RISK_ON LIKE 'Trade Day - 1';
UPDATE MI_ISO_PROFILE_PRODUCT SET BID_SUBMISSION_ISO_ON='TRADE_HOUR' WHERE BID_SUBMISSION_ISO_ON LIKE 'Trade Hour';
UPDATE REGISTRATION_STATUS SET REGISTRATION_STATUS='REGISTERED' WHERE REGISTRATION_STATUS='Registered';
UPDATE REGISTRATION_STATUS SET REGISTRATION_STATUS='PENDING' WHERE REGISTRATION_STATUS!='Registered';